const cn = {
  general: {
    home: "主页",
    next: "下一项",
    ok: "确认",
    done: "完成",
    cancel: "取消",
    confirm: "Confirm",
    apply: "应用",
    save: "保存",
    select: "选择",
    connect: "连接",
    disconnect: "断开",
    yes: "是",
    no: "否",
    error: "错误",
    back: "返回",
    delete: "删除",
    remove: "移除",
    online: "在线",
    offline: "离线",
    cloud: "Cloud",
    remote: "遥控",
    preset: "预设",
    camera: "相机",
    focuser: "电动调焦座",
    filter_wheel: "滤镜轮",
    filter: "滤镜",
    exposure: "曝光",
    binning: "像素合并",
    action: "动作",
    scope_type: "望远镜类型",
    solver_type: "解析类型",
    type: "类型",
    gain: "增益",
    offset: "偏置",
    format: "格式",
    iso: "ISO",
    count: "连拍",
    delay: "延时",
    status: "状态",
    target: "目标",
    angle: "角度",
    sep_profile: "SEP文件",
    direction: "方向",
    rotation: "旋转",
    automatic: "自动",
    manual: "手动",
    progress: "处理",
    position_angle: "PA",
    details: "Details",
    skip: "Skip",
    updated: "Updated",
    new: "New",

    azimuth: "方位角",
    altitude: "高度角",
    tags: "标签",
    filename: "文件名",
    size: "尺寸",
    frame: "画幅",
    temperature: "温度",
    name: "名称",
    date: "日期",
    resolution: "分辨率",

    selectFile: "Select file",
    selectFolder: "Select folder",
    selectedDir: "selected folder",
    new_folder: "Enter new folder name",
    create_new_folder: "Create new folder in",
    empty_folder: "Folder is Empty",

    train: "Train",
    no_data_found: "No data found",
    track: "Track",
    jobs: "Jobs",
    category: "Categories",
    profile: "Profile",
    arcmin: "arcmin",
    calculate: "Calculate",
    update: "Update",
    center: "Center",
    learnMore: "Learn more",

    select_option: "请选择...",
    search: "查找...",
    no_results: "无结果",
    on: "开",
    off: "关",
    go: "前往",
    add: "添加",
    edit: "编辑",
    refresh: "刷新",
    reset: "重置",
    reset_all: "全部重置",
    start: "开始",
    stop: "停止",
    stopping: "停止中",
    clear: "清除",
    solve: "解析",
    parked: "复位",
    unparked: "取消复位",
    open: "打开",
    close: "关闭",
    opened: "打开",
    closed: "关闭(d)",
    enable: "允许",
    disable: "禁止",
    selectTime: "选择时间",
    set: "设置",

    // Confirm Delete Alert
    alert_confirm_delete_title: "确认删除",
    alert_delete_profile_body: "你确认要删除已选择的文件吗？",
    alert_delete_scope_body: "你确定要删除已选择的望远镜吗？",

    // Confirm
    alert_confirmation_title: "Confirmation",
    alert_create_preset_body:
      "Are you sure you want to create preset with this name?",

    network_error: "请确认StellarMate已联网",
    internet_required: "请确认你已经联网",
    alert_comm_error_title: "通信错误",
    alert_comm_error_body: "与StellarMate通信失败.请确认你已经连接网络",
    ekoslive_down_title: "EkosLive停止运行",
    ekoslive_down_body:
      "EkosLive不在工作中,尝试重启StellarMate或者联系StellarMate技术支持.",
    kstars_down_title: "KStars停止工作",
    kstars_down_body:
      "KStars不在工作中,尝试重启StellarMate或者联系StellarMate技术支持.",
    reset_default: "恢复默认设置",
    external_storage: "外部存储器",
  },
  darkLibrary: {
    title: "暗场库",
    darks: "暗场",
    defects: "Defects",
    prefer: "Prefer",
    create_darks_title: "创建暗场",
    create_defects_title: "Create Defect Map",
    view_masters_title: "View Masters",
    progress: "Progress",

    create_darks: {
      exposure_range: "曝光范围",
      to: "To",
      temp_range: "温度范围",
      binning: "像素合并",
      binningOne: "1x1",
      binningTwo: "2x2",
      binningFour: "4x4",
      total_images: "总共",
    },

    create_defect_map: {
      master_dark: "主暗场",
      bad_pixels: "坏点",
      hot_pixels: "热噪",
      generate_map: "生成图像",
      save_map: "保存",
      deviation: "σ",
    },
  },
  achievements:{
    score: "Total Score",
    badge: "Badge",
    achievements: "Achievements",
    unlocked: "ACHIEVEMENT UNLOCKED",
    points: "Points",
    completed: "Completed",
    notCompleted: "Not completed",
    capture_preview_title: "First Light!",
    ten_sequences_title: "So it begins!",
    mount_goto_title: "Magic Fingers",
    video_recording_title: "Director’s Cut",
    weather_check_title: "Cloud Magnet",
    live_stacking_title: "Let there be details",
    create_darks_title: "Embrace the dark side",
    create_defect_title: "Cosmic Makeup",
    import_mosaic_title: "Mosaic Weaver", 
    messier_captured_title: "MXXXX (e.g. M1)",
    all_messier_title: "Cosmic Marathon",
    scheduler_title: "Robotic Master", 
    capture_master_title: "Sky Master",
    capture_legend_title: "Sky Legend",
    paa_title: "Perfectionist",
    guide_rms_title: "Bullseye!",

    capture_preview_description: "Capture a Preview",
    ten_sequences_description: "Capture a sequence with 10 counts",
    mount_goto__description:  "Use Target GOTO by holding on the object for 3 seconds when the new image is captured",
    video_recording_description: "Record video for 1 minute",
    weather_check__description: "Use Cloud Map in weather info, Zoom in to at least 8x to check weather",
    live_stacking_description:  "Live stacking. Perform at least 5 images",
    create_darks_description:  "Create Darks of total 50 Images",
    create_defect_description: "Generate hot / cold pixels in Defect map above 80",
    import_mosaic_description: "Import Mosaics from telescopios",
    messier_captured_description: "A messier object is captured",
    all_messier_description: "All Messier objects were captured",
    scheduler_description: "Finish a scheduler job worth 2 or more hours of image data.",
    capture_master_description: "Capture a total of 500 images",
    capture_legend_description: "Capture a total of 1000 images",
    paa_description: "Finish PAA with box error lower than 30 arcsecs.",
    guide_rms_description: "Achieve total RMS guiding below 0.5 arcsecs.",
},
  tourGuide:
  {
    tour_guide: "Tour Guide",
    previous: "Previous",
    finish: "Finish",
    title_devices_list: "StellarMate Devices List",
    title_device_actions: "Device Actions",
    title_profles: "Profiles",
    title_port_selector: "Port Selector",
    title_trains: "Optical trains",
    title_weather_bar: "Weather bar",
    title_cloud_report: "Cloud Report",
    title_next: "What's next?",
    
    title_focus: "Focus",
    title_align: "Align",
    title_guide: "Guide",
    title_capture: "Capture",
    title_mount: "Mount",
    title_observatory: "Observatory",
    title_scheduler: "Scheduler",
    title_indi: "INDI Control Panel",
    title_quick_controls: "Quick Controls",
    title_preview: "Preview",
    title_framing: "Framing",
    title_live_video: "Live Video",
    title_stop: "Stop",
    title_live_stacking: "Live Stacking",
    title_quick_settings: "Qucik Camera Settings",
    
    title_targets_info: "About Targets",
    title_search_bar: "Search bar",
    title_time_controls: "Time Controls",
    title_target_controls: "Targets Controls",
    title_object_info: "Object info",
    title_fov: "Target Field Of View",
    title_target_action: "Target Action",

    description_devices_list: "This is the list of automatically discovered and manually added StellarMate units. Tap RESCAN to detect new StellarMate units on the network.",
    description_device_actions: "Remove a device from the list, perform a factory reset, or log out.",
    description_profles: "Manage your astronomy equipment in Equipment Profiles. All equipment must be powered and connected to StellarMate before starting a profile. Once a profile is started, configure the Optical Trains and then tap Ekos to start your astrophotography session.",
    description_port_selector: "After a profile is started for the first time, select the serial and/or network settings for your devices.",
    description_trains:
    "Set up how your equipment is arranged using Optical trains. Assign each device to a specific function. Create a train for each camera.",
    description_weather_bar:"Brief weather report and current site Bortle class",
    description_cloud_report: "3-hours Cloud overlay.", 
    description_next: "Explore applicable astronomical targets by tapping the Targets tab. Use Go & Solve to center your target in the camera frame. Open the Framing Assistant to achieve the perfect desired orientation. Head over to Ekos tab to set up imaging sequences and live stack images.", 

    description_focus: "Focus the camera by using a motorized focuser.",
    description_align: "Center the mount exactly on target by plate-solving an image.",
    description_guide: "Keep the mount locked to your target during tracking to enable long exposures.",
    description_capture: "Create sequences to capture images using configurable settings. Manage filter wheel settings and Dark Library.",
    description_mount: "Toggle tracking, parking, and meridian flip settings. Configure auto-park.",
    description_observatory: "Control dome and dust-cap equipment.",
    description_scheduler: "Automate complete astrophotography session by selecting target and sequence file. Import mosaics from Telescopius.",
    description_indi: "Direct low-level access to equipment properties.",
    description_quick_controls: "Quick access to mount, camera, and rotator controls.",
    description_preview: "Capture a single preview frame.",
    description_framing: "Loop exposures indefinitely until stopped",
    description_live_video: "Start live video streams and record videos to storage.",
    description_stop: "Stop any ongoing exposures or recordings.",
    description_live_stacking: "Live stack images to increase signal to noise ratio. If an existing capture sequence is running, live stacking will use incoming images otherwise it will loop exposures using settings in Quick Camera Settings.",
    description_quick_settings: "Select active train and configure camera and filter wheel settings.",
    
    description_targets_info: "Targets is the StellarMate Planning tool to streamline your observation session. Search from thousands of objects and filter them using simple criteria. Use the Framing Assistant to frame your targets." ,
    description_search_bar:
      "Filter objects in the existing list or search for new objects by entering the name and tapping the search button.",
    description_time_controls:
      "If Ekos is offline, adjust the target date and time calculations.",
    description_target_controls:
      "Check out twilight information, manage FOVs, adjust filters, and select object types.",
    description_object_info: "Object magnitude, rise, transit, and set times.",
    description_fov: "Tap to enter Framing Assistant mode.",
    description_target_action: "Add target to favorites or custom list. Command a GOTO only or a GOTO followed by capture and solve. If Ekos is offline, schedule the target.",
  },
  tooltip: 
  {
    placeholder: "Placeholder %{0} or %{1}",
    placeholder_file: "The name of the .esq file, without extension.",
    placeholder_date: "The current time and date when the file is saved.",
    placeholder_type: "The frame type e.g: 'Light', 'Dark'",
    placeholder_exp: "The exposure duration in seconds.",
    placeholder_filter: "The active filter name.",
    placeholder_seq: "The image sequence identifier where * is the number of digits used (1-9), This tag is mandatory and must be the last element in the format",
    placeholder_target: "The Target name.",
    format_title: "Format is used to define the image file names by the use of placeholder tags.",
    suffix: "Number of digits used to append the sequence number to the filename",
    paa_desc: "Use plate-solving method for Polar Alignment. Plate solving is slower but provides more accurate results.",
    plate_solving: "Uses plate solving to track what the corrected alignment error is during the Refresh process. User should try to reduce the error in the Updated Err line below and minimize the size of the arrows.",
    movestar_title:"Move Star and Calc Error",
    movestar_desc: "Like Move Star, But Ekos attemps to track the star being moved and estimates the current alignment error when it can."
  },
  splash: {
    checking_for_updates: "检测更新中...",
    downloading_package: "下载更新中...",
    installing_update: "安装更新包...",
    channel_update: "Channel switching in progress...",
    upto_date: "已是最新版本",
    update_installed: "更新已安装",
    loading: "加载中...",
  },
  validations: {
    username_required: "请输入用户名",
    username_tooshort: "至少需要3个字母",
    username_toolong: "不能超过64个字母",
    username_invalid: "用户名含有非法字符",
    password_required: "请输入密码",
    password_invalid: "至少需要6位",
    confirm_password_required: "请确认密码",
    confirm_password_mismatch: "密码错误",
    email_required: "请填写邮箱",
    email_invalid: "邮箱地址无效",
    license_required: "请输入许可证密钥",
    serial_required: "请输入序列号",
    new_scope_vendor: "请输入有效用户名",
    new_scope_model_invalid: "请输入有效的模型",
    new_scope_aperture_invalid: "请输入有效的光圈",
    new_scope_focal_length_invalid: "请输入有效的焦距",
    new_scope_focal_ratio_invalid: "Enter a valid focal ratio",
  },
  progress: {
    please_wait: "请稍候 ...",
    establishing_connection: "正在建立连接",
    cameras: "获取相机",
    mounts: "获取赤道仪",
    scopes: "获取望远镜",
    filter_wheels: "获取滤镜轮",
    registering: "注册中",
    registered: "注册完毕",
    authenticating: "登录中",
    authenticated: "登录完毕",
    checking_kstars: "检查KStars",
    kstars_open: "KStars启动",
    checking_ekoslive: "检查EkosLive...",
    ekoslive_connected: "EkosLive已连接",
    starting_ekos: "启动Ekos...",
    getting_devices: "获取设备...",
    loading_settings: "加载配置...",
    register_device: "Scanned QR Code, Registering Device: ",
  },
  welcome: {
    register_new_device: "注册新的设备？",
    have_existing_account: "已存在一个账号？",
    require_sm_plus_pro: "如果已购买，请注册",
  },
  device_scanner: {
    scanning: "正在联网获取StellarMate设备中，请稍侯",
    qr_scan: "扫描您的设备上的二维码",
  },
  statuses: {
    Idle: "闲置",
    prep: "Prep",
    run: "Run",
    Aborted: "中断",
    "Calibration error": "校准错误",
    Capturing: "正在捕获",
    "In Progress": "进行中",
    "Setting Temperature": "设置温度",
    Slewing: "反转中",
    Calibrating: "校准中",
    Tracking: "追踪中",
    Guiding: "导星中",
    Parking: "复位中",
    "User Input": "请输入",
    Complete: "完成",
    Suspended: "暂停",
    Parked: "复位",
  },
  connect: {
    register_welcome: "请登录您的Stellarmate账号以同步设备.",
    welcome_heading: "欢迎使用",
    welcome_description:
      "请确认您已连接至StellarMate的热点或StellarMate与您的设备处于同一网络中",
    welcome_rescan: "点击”重新扫描”扫描局域网中的StellarMate",
    device_unreachable: "设备无法访问！ 请检查电源和网络设置",
    login_mismatch:
      "认证失败。App 密码与stellarmate.com上设定的密码不一致。请使用正确密码再次登入。",
    old_stellarmate_heading: "版本过旧。请更新!",
    old_stellarmate_description:
      "您正在使用 StellarMate OS 的旧版本。若想继续使用本应用，请务必更新至  StellarMate 的最新版本。",
    primary: "主镜",
    guide: "导星相机",
    scope: "导星镜",
    btn_rescan: "重新扫描",
    btn_port_select: "端口选择",
    btn_sync_gps: "同步GPS",
    btn_dslr_setup: "相机设置",
    btn_clear_driver_config: "清除设备设置",
    scan_in_progress: "正在扫描 ...",
    connection_in_progress: "正在连接StellarMate...",
    registration_in_progress: "正在注册StellarMate...",
    logging_in_progress: "正在登陆StellarMate...",
    connecting: "连接中...",
    logging: "登陆中...",
    generic: "Generic Serial",
    select_driver: "Please select device type and driver",

    ip_address: "请输入IP地址",
    login_register: {
      heading: "认证",
      heading_online: "请登录stellarmate.com",
      connect_to_internet: "您必须联网",
      connect_to_sync: "此操作仅用于同步您的帐户一次.",
      reset_app:
        "提示：你可以通过转到“关于”选项，单击“重置应用程序”按钮，然后重新启动应用程序，将应用程序与你的在线帐户重新同步",
      no_valid_device: "无有效的设备信息",
      setup_guide: "设置导星设备",
      register: "注册",
      login: "登入",
      serial: "序列号#",
      license: "许可证密钥",
      username: "用户名",
      password: "密码",
      confirm_password: "确认密码",
      first_name: "名",
      last_name: "姓",
      email: "邮箱",
    },
    device_manager: {
      alert_confirm_remove_title: "确认移除",
      alert_confirm_remove_body: "确定移除该设备？",
      btn_sign_out: "登出",
    },
    profile_manager: {
      heading: "配置文件",
    },
    port_selector: {
      connect_all: "连接所有",
    },
    manually_add_device: {
      heading: "手动添加设备",
      btn_add_device: "添加设备",
      alert_unreachable_title: "发生错误",
      alert_unreachable_body:
        "尝试在指定的IP地址处寻找设备时出错，请检查IP地址，然后重试",
    },
    device_scanner: {
      no_device_before_scan: "未检测到设备，请运行扫描程序",
      no_device_after_scan: "扫描完成，未发现设备",
      auto_scanned: "自动扫描",
      manually_added: "手动添加",
      add_a_device: "添加设备",
      devices_detected: "检测完毕",
      no_network_found: "未发现设备，请确认您的网络连接",
    },
    add_profile: {
      add_profile: "添加配置文件",
      edit_profile: "编辑配置文件",
      mount: "赤道仪",
      ccd: "主相机 1",
      dome: "Dome",
      guider: "主相机 2",
      ao: "自适应光学设备",
      weather: "天气设备",
      aux1: "辅助设备1",
      aux2: "辅助设备2",
      aux3: "辅助设备3",
      aux4: "辅助设备4",
    },
    add_scope: {
      add_scope: "添加望远镜",
      edit_scope: "编辑望远镜",
      vendor: "厂商",
      aperture: "口径 (mm)",
      focal_length: "焦距 (mm)",
    },
    auto_detect: {
      alert_auto_detect_title: "Auto Detect Instructions",
      alert_auto_detect_body:
        "Unplug ALL equipment from StellarMate then press Ok. Then plug them one by one to detect the device type and driver. After each device is plugged, you need to confirm the driver.",
      alert_mapped_title: "Device Mapping",
      alert_mapped_body: "Device serial port is successfully mapped.",
      alert_missing_driver_title: "缺少设备",
      alert_missing_driver_body: "你必须先选择一个设备",
    },
    dslr_setup: {
      width: "宽",
      height: "高",
      pixel_width: "像素宽",
      pixel_height: "像素高",
    },
  },
  targets: {
    now: "现在",
    night: "夜晚",
    rise: "升起",
    moon: "月亮",
    sun: "太阳",
    search: "搜索",
    cam_width: "Camera Width",
    cam_height: "Camera Height",
    phases: {
      new_moon: "新月",
      full_moon: "满月",
      first_quarter: "上弦月",
      third_quarter: "下弦月",
      waxing_crescent: "娥眉月",
      waxing_gibbous: "盈凸月",
      waning_crescent: "残月",
      waning_gibbous: "亏凸月",
    },
    lists: "列表",
    framing_assistant: "Framing Assistant",
    target_rotation: "目标方位角",
    current_rotation: "Current Rotation",
    rotate_capture: "Rotate & Capture",
    goto_rotate: "GOTO & Rotate",
    angular_offset: "Angular Offset",
    no_objects_in_list: "No Objects found, please adjust or reset the filters.",
    go_and_solve: "Go & Solve",
    fov_profile: "FOV Profile",
    fov_width: "FOV Width",
    fov_height: "FOV Height",
  },
  ekos: {
    heading: "Ekos",
    tgl_mount: "赤道仪",
    tgl_solution_bar: "状态栏",
    tgl_sequence: "拍摄队列",
    tgl_properties: "属性",
    alert_ekos_offline_title: "Ekos离线中",
    alert_ekos_offline_body: "Ekos目前处于离线状态，是否开启设备匹配?",
    ekos_dialog: {
      auto_closes_in: "Auto closes in",
    },
    controls_bar: {
      mount_speed: "赤道仪转速",
      centering: "居中",
      find: "寻找",
      max: "最大",
    },
    collapse_align: {
      heading: "导星",
      action_sync: "同步",
      action_slew: "回转至目标",
      action_nothing: "不进行动作",
      solver_backend: "Backend",
      control: "控制",
      solve: "拍摄 & 解析",
      load: "Load & Slew",
      polar: "极轴校准",
      accuracy: "Accuracy",
      settle: "Settle",
      dark: "Dark",
      arcsec: "arcsec",
      ms: "ms",
      xAxis: "Iterations",
      yAxis: "Error (arcsec)",
      refresh_rate: "Refresh Rate",
      manualRotator: {
        heading: "Manual Rotator",
        currentPA: "Current PA",
        targetPA: "Target PA",
        another_image: "Take another Image",
      },
      alignSettings: {
        rotator_control: "Rotator Control",
        use_scale: "Use Scale",
        use_position: "Use Position",
      },
      calibrationSettings: {
        pulse: "Pulse",
        maxMove: "Max Move",
        twoAxis: "Two axis",
        squareSize: "Auto square size",
        calibrateBacklast: "Remove DEC backlash in guide calibration",
        resetCalibration: "Reset Guide Calibration After Each Mount Slew",
        reuseCalibration: "Store and reuse guide calibration when possible",
        reverseCalibration:
          "Reverse DEC on pier-side change when reusing calibration",
      },
    },

    collapse_camera: {
      heading: "相机设置",
      type_light: "亮帧",
      type_bias: "偏置",
      type_flat: "平场",
      type_dark: "Dark",
      format_fits: "FITS",
      format_native: "原生",
      cooling_unavailable: "冷却不可用",
      btn_add_to_sequence: "添加到拍摄队列",
      btn_loop: "循环",
    },
    capture_presets: {
      heading: "预设",
    },
    capture_limits: {
      heading: "Limit Settings",
      guiding_deviation: "Guiding Deviation <",
      guiding_deviation_unit: '"',
      focusHFR: "自动对焦如果HFR >",
      focusHFR_unit: "pixels",
      focusDeltaT: "自动对焦如果ΔT° >",
      focusDeltaT_unit: "°C",
      refocusN: "Refocus every",
      refocusN_unit: "分",
    },
    capture_filters: {
      heading: "Filter Settings",
      auto_focus: "Auto Focus",
      lock_filter: "Lock Filter",
    },
    targets_filters: {
      object_type: "Object Type",
      alt: "Alt",
    },
    capture_auto_calibration: {
      heading: "自动校准",
      flat_source: "Flat Source",
      flat_duration: "Flat Duration",
      dust_builtin: "Dust Cover with Built-in Flat Light",
      dust_external: "Dust Cover with External Flat Light",
      wall: "Wall",
      az: "Az",
      adu: "ADU",
      tolerance: "Tolerance",
      parkMount: "Park Mount",
      parkDome: "Park Dome",
    },
    capture_file: {
      filename: "File Name",
      heading: "File Settings",
      prefix: "Prefix",
      script: "Script",
      directory: "Directory",
      ts: "TS",
      duration: "Duration",
      suffix: "Suffix",
      usb: "USB Unmounted successfully",
      unmount: "Unmount"
    },
    collapse_dome: {
      heading: "窗口 & 圆顶",
      cap: "窗口",
      dome: "圆顶",
      shutter: "Shutter",
      domeSlaving: "Dome Slaving",
      params: "Parameters",
      measurements: "Measurements",
      autosync_threshold: "Autosync Threshold (deg)",
      radius: "Radius (m)",
      shutter_width: "Shutter Width (m)",
      n_displacement: "N Displacement (m)",
      e_displacement: "E Displacement (m)",
      up_displacement: "Up Displacement (m)",
      ota_offset: "OTA Offset (m)",
    },
    collapse_focus: {
      heading: "调焦",
      hfr: "HFR",
      hfr_plot: "HFR图像",
      focus_in: "In",
      focus_out: "Out",
      steps: "Steps",
      settings: {
        suspendGuiding: "Suspend Guiding",
        autoSelectStar: "Auto Select Star",
        subframe: "Sub Frame",
        fullfield: "Full Field",
        dark: "Dark Frame",
        annulus: "Annulus",
      },
      process: {
        title: "Process",
        detection: "Detection",
        algorithm: "Algorithm",
        threshold: "Threshold",
        effect: "Effect",
        averageOver: "Average Over",
        kernelSize: "Kernel Size",
        numOfRows: "Num. of Rows",
        sigma: "Sigma",
      },
      mechanics: {
        title: "Mechanics",
        initialStepSize: "Initial Step Size",
        maxTravel: "Max Travel",
        maxStepSize: "Max Step Size",
        backlash: "Backlash",
        outStepMultiple: "Out Step Multiple",
      },
    },
    collapse_guide: {
      total_rms_plot: "RMS",
      scope_primary: "Primary",
      guidingRate: "Guiding Rate",
      via: "Via",
      box: "Box",
      effects: "Effects",
      dither: "Dither",
      frequency: "Frequency",
      every: "every",
      frames: "frames",
      gpg: "GPG",
      directions: "Directions",
      dec: "DEC",
      swap: "Swap",
      east: "+",
      west: "-",
      north: "+",
      south: "-",
      subframe: "Subframe",
      autostar: "Auto Star",
      aggressiveness: "Aggressiveness",
      rarms: 'RA RMS"',
      derms: 'DE RMS"',
      totalrms: 'Total RMS"',
      advanced: "Advanced",
      clear_model: "Clear Calibration Model",
      yAxis: "Drift (arcsec)",
    },
    collapse_observatory: {
      heading: "Observatory",
    },
    collapse_polar: {
      heading: "极轴校正",
      mount_direction: "赤道仪导航",
      manual_slew: "Manual Slew",
      west: "西",
      east: "东",
      mount_rotation: "赤道仪回转",
      refresh: "刷新",
      fov_error: "无效：视场广度必须为30角分以上",
      polar_error: "极轴错误",
      az_error: "AZ error: ",
      al_error: "AL error: ",
    },
    collapse_sequence: {
      progress: "进度",
      sequence: "队列",
      overall_progress: "总进度",
      sequences: "所有队列",
      no_sequences: "无拍摄队列，您可以在相机设置中添加",
    },
    collapse_mount: {
      meridian_flip: "Meridian Flip",
      flip_if_ha: "Flip if HA >",
      flip_if_ha_unit: "°",
      pierside: "Pier Side",
      auto_park: "Auto Park",
      auto_park_everyday: "Every day",
      park_at: "Park at",
      reset_options: "Reset Options",
      min_alt: "Min. Alt",
      max_alt: "Max. Alt",
      enable_alt_limits: "Enable Alt Limits",
      enable_ha_limits: "Enable HA Limits",
      max_ha: "Max. HA (hours)",
      clear_model: "Clear Model",
      east: "E",
      west: "W",
      east_long: "East (pointing west)",
      west_long: "West (pointing east)",
    },
    modal_add_to_seq: {
      heading: "添加到队列",
    },
    modal_goto_sync: {
      heading: "Goto&同步",
      category: "星表类型",
      btn_goto: "Goto",
    },
    mount_status_bar: {
      ra: "RA",
      de: "DE",
      az: "AZ",
      at: "AL",
      ha: "HA",
    },
    camera_status_bar: {
      bin: "Bin",
    },
    solution_bar: {
      dra: "赤经偏差",
      dde: "赤纬偏差",
      arcsec: '"',
      pix: "像素",
      rot: "旋转角",
      fov: "视场",
    },
    mount_overlay: {
      right_asc: "赤经",
      declination: "赤纬",
    },
    histogram: {
      mean: "Mean",
      median: "Median",
      bit_depth: "Bit Depth",
      non_linear_histogram: "Non-Linear Histogram",
    },
    livestacking: {
      auto_dark: "Auto Dark",
      plate_solve: "Plate Solve",
      background: "Background",
      saturation: "Saturation",
      contrast: "Contrast",
      sigma_clipping: "Sigma Clipping",
      noImages: "No Live Stacking Images found",
    },
    scheduler: {
      scheduler: "Scheduler",
      j2000: "J2000",
      fits: "FITS File",
      priority: "Priority",
      profile: "Profile",
      startupConditions: "Job Startup",
      JobConstraints: "Job Constraints",
      completionConditions: "Job Completion",
      observatoryStartup: "Observatory Startup",
      abortedJobManagement: "Aborted Job",
      observatoryShutdown: "Observatory Shutdown",
      alt: "Alt >",
      moon: "Moon >",
      twilight: "Twilight",
      artifHorizon: "Artificial Horizon",
      sequenceCompletion: "Sequence Completion",
      repeatFor: "Repeat for",
      repeatUntilTerminated: "Repeat Until Terminated",
      repeatUntil: "Repeat until",
      unparkDome: "UnPark Dome",
      unparkMount: "UnPark Mount",
      uncap: "UnCap",
      warmCCD: "Warm CCD",
      none: "None",
      queue: "Queue",
      immediate: "Immediate",
      rescheduleErrors: "Reschedule Errors (seconds wait)",
      no_jobs: "No Jobs in the queue",
      err_loading_folders: "Error loading folders",
      err_loading_fits: "Error loading .fits files",
      err_delete_file: "Error deleting file",
      add_job: "Add Job",
      start_jobs: "Start & Stop Jobs",
      culimination: "Culmination Offset",
      create_jobs: "Create Jobs",

      mosaic: {
          import: "Import Mosaic",
          planner: "Mosaic planner"
      }
    },
    summary: {
      empty: "No summary data available",
      deviation: "Deviation",
      inactive: "Inactive",
  }
  },
  optical_train: {
   optical_trains: "Optical Trains",
   telescope: "Telescope / Lens",
   create_new: "Create New",
   dslr_lens: "DSLR Lens",
   focal_ratio: "Focal Ratio",
   tooltip:{
    title: "Select the device that receives the guiding correction pulses",
    subject: "This can be one of the following devices:",
    mount_device: "If the Mount can receive guiding correction pulses, then it is best to select it so that the pulses are directly sent to the mount. This is the recommended option.",
    st4_device: "If using an ST4 cable between the guide camera and mount, then you should select the Guide Camera as the Guider.",
    dedicated_device: "If using a dedicated guider interface device (like Shoestring GPUSB) then select it as the Guider",
    dedicated: "Dedicated",
    filterWheel: "Select a filter wheel. This must be a standalone filter wheel connected to StellarMate via USB. If you have a filter wheel that is embedded in a camera, leave this field empty."
}
},
  status: {
    system: "系统",
    info: "信息",
    software: "软件",
    cpu: "CPU",
    ram: "RAM",
    storage: "内存",
    stable: "稳定版",
    beta: "Beta版",
    wifi_network: "无线网 IP",
    hotspot_network: "热点 IP",
    ethernet_network: "以太网 IP",
    model: "型号",
    version: "版本",
    hostname: "主机名",
    time: "时间",
    release_type: "版本类型",
    updates: "更新选项",
    hotspotMode: "Hotspot Mode",
    wifiNetwork: "Wifi Network",
    wifiBand: "WiFi Band",
    update_available: "可用更新",
    update_unavailable: "暂不可用更新",
    update_in_progress: "更新中",
    btn_vnc: "远程桌面 (VNC)",
    btn_web_manager: "网页管理器",
    btn_restart: "重启",
    btn_shutdown: "关机",
    btn_manage_wifi: "更改网络",
    btn_enable_direct_ethernet: "启用以太网",
    btn_disable_direct_ethernet: "禁用以太网",
    btn_enable_hotspot: "启用热点",
    btn_disable_hotspot: "禁用热点",
    btn_change_hostname: "更改主机名",
    btn_check_for_updates: "检查更新",
    btn_update_now: "立即更新",
    btn_update_in_progress: "更新中...",
    btn_factory_reset: "恢复出厂设置",
    btn_change_resolution: "变更协议",
    btn_later: "稍后",
    btn_resize_fs: "重置SD",
    btn_continue: "继续",
    information_ekos_offline:
      "Ekos is offline. Please start the equipment profile directly or via the Scheduler.",
    no_camera_detected: "没有相机被选择或者相机已离线",

    alert_device_offline_title: "设备已离线",
    alert_device_offline_body: "设备似乎已经离线。是否要登录激活？",
    alert_restart_title: "重启StellarMate",
    alert_restart_body: "您的设备即将重启。重启后请尝试再次连接。",
    alert_shutdown_title: "关闭StellarMate",
    alert_shutdown_body: "您的设备即将关闭，重新使用需要手动开启。",
    alert_resize_title: "重置 microSD Card 大小",
    alert_resize_body: "StellarMate会扩展到全部SD卡容量. 请重启StellarMate",
    alert_resize_btn_resize: "Resize",
    alert_hotspot_enable_title: "启用热点",
    alert_hotspot_enable_body:
      "启用热点会使StellarMate断开当前加入的wifi网络，并启动自己的热点。若继续使用StellarMate，您需要连接到此热点网络。是否继续?",
    alert_hotspot_post_enable_title: "请连接到热点",
    alert_hotspot_post_enable_body:
      "您现在可以连接到“stellarmate”热点，并在连接后点击确认以继续",
    alert_hotspot_disable_body:
      "禁用热点将使StellarMate连接到其先前连接过的无线网络。热点禁用时，您需要在同一网络继续使用StellarMate。是否继续?",
    alert_factory_reset_body: "恢复出厂设置完成，请立即重启StellarMate",
    alert_factory_reset_confirmation_body:
      "Are you sure you want to reset device to factory settings? All settings will be wiped. This action is irreversible!",
    alert_forget_wifi_title: "删除Wifi",
    alert_forget_wifi_body:
      "断开并删除当前Wifi将使StellarMate启用自己的热点（如果未连接到以太网）。您将需要连接到此热点才能继续使用。是否继续？",
    alert_join_wifi_title: "加入Wifi网络",
    alert_join_wifi_body:
      "加入Wifi网络将关闭StellarMate的热点（如果已启动）。若继续使用StellarMate，请确保您在同一网络上。是否继续？",
    alert_change_resolution_title: "成功!",
    alert_change_resolution_body: "您现在可以重启StellarMate令变更生效",
    alert_change_release_title: "测试频道",
    alert_change_release_body:
      "Are you sure you want to switch to the unstable and unsupported beta channel?",
    alert_direct_ethernet_title: "Direct Ethernet",
    alert_direct_ethernet_connect_body:
      "Connect Ethernet cable directly between StellarMate and your PC. Set your PC IP address to 192.168.100.2 and gateway to 192.168.100.1",
    alert_direct_ethernet_disconnect_body: "Remove direct Ethernet cable.",
    alert_clear_all_driver_config_title: "Clear All Driver Configuration",
    alert_clear_all_driver_config_body:
      "Are you sure you want to delete all driver configuration?",
    alert_update_complete_title: "SM OS Update",
    alert_update_complete_body: "Update complete, please restart StellarMate.",
    alert_network_error_title: "Network error",
    alert_network_error_body: "Failed to query network information",
    alert_delete_directory_message: "You want to delete {0} directory and all files under it?",

    alert_permission_title: "Location permission",
    alert_permission_description: "StellarMate App requires Location information to synchronize StellarMate gadget location to the App location. Do you want to proceed?",

    alert_remote_isactive: "Failed to check if Remote support is active, Is your Stellarmate OS up to date? ",
    alert_remote_start: "Could not start the Remote support: ",
    alert_remote_stop: "Could not stop the Remote support: ",
    alert_remote_id: "Could not find Remote support ID", 
    alert_remote_failed: "Failed to get Remote support ID: ",
    alert_remote_not_found: "No Remote support found: ",

    change_resolution_modal: {
      mode: "模式",
    },
    change_hostname_modal: {
      new_hostname: "新主机名",
    },
    change_wifi_modal: {
      heading: "加入网络",
      ssid: "SSID",
      err_wifi: "搜寻Wifi时遇到了问题，请重试",
    },
    change_band_modal: {
      heading: "Change Band",
      band: "Band",
      channel: "Channel",
    },
    vnc_view: {
      heading: "远程桌面(VNC)",
      alert_unreachable_title: "VNC 无法访问",
      alert_unreachable_body:
        "尝试建立与VNC查看器的连接时似乎遇到了问题，请重试",
    },
    web_manager_view: {
      alert_unreachable_title: "网页管理器无法访问",
      alert_unreachable_body:
        "尝试建立与网页管理器的连接时似乎遇到了问题，请重试",
    },
  },
  settings: {
    heading: "设置",
    language: "语言",
    high_bandwidth: "高带宽模式",
    transfer_images: "传输图像",
    notifications: "通知",
    sounds: "声音",
    cloud_storage: "云存储",
    auto_sync: "自动同步",
    location: "位置",
    reset_app: "Reset App",
    reset_app_body: "Purge all App settings?",
  },
  cloud: {
    heading: "云服务",
    btn_filters: "筛选",
    btn_gallery: "图库",
    btn_offline_viewer: "Offline Viewer",
    btn_cloud_viewer: "Cloud Viewer",
    no_images_title: "找不到图像",
    no_images_body: "请尝试更改筛选条件",
    no_selected_title: "没有选择图像",
    no_selected_body: "从图库中选择一张图片",
    cloud_disabled_title: "云服务已禁用",
    cloud_disabled_body: "请转到设置并启用云服务以访问此选项卡",
    pro_plan_body: "云存储仅适用于高级用户",
    alert_cannot_download_title: "无法下载",
    alert_cannot_download_body: "尝试下载时出错，请重试",
    alert_confirm_delete_title: "是否确定?",
    alert_confirm_delete_body: "真的要删除{0}吗？删除后数据将无法恢复",
    filters_drawer: {
      field: "域",
      condition: "条件",
      value: "值",
      btn_add_filter: "添加筛选条件",
      airmass: "大气光学质量",
      object: "对象",
      contains: "包含",
    },
    gallery_drawer: {
      all: "全部",
      h1: "1h",
      h24: "1d",
      d7: "7d",
      m1: "1m",
      y1: "1y",
      images: "图像",
      btn_sort: "分类",
      btn_delete_all: "全部删除",
      ascending: "升序",
      descending: "降序",
      alert_no_images_title: "无图像",
      alert_no_images_body: "没有可以删除的图像",
      alert_delete_all_body: "确定删除选定的 {0} 张图片吗? 此操作无法恢复",
    },
    info_drawer: {
      add_tags_here: "在这里添加标签",
      captured_on: "已捕获",
    },
  },
  about: {
    heading: "关于",
    bundle: "Bundle",
    copyright_line1:
      "StellarMate is developed by Ikarus Technologies. © 2017-2022",
    copyright_line2: "Background image by Alamri Observatory",
  },
  messages: {
    polar_idle:
      "This tool provides a simple method to polar align a German equatorial mount. Park your mount to home position where it points toward the celestial pole with the counter weight down. Select mount direction and speed and then click Start to begin the process. If you do not have a view of the pole, use the SkyMap or Ekos mount control to point anywhere, preferably near the meridian, choose East or West according your side, lower the rotation angle if necessary, and click Start.",
    alert_directions_not_found:
      "Coordinates not found, Please frame your target or enter coordinates manually.",
      manual_rotator: "Rotate camera by the indicated angle and then take an image to update the position angle",
      welcome: "Welcome to StellarMate"
  },
  ekosLivePro: {
      pushNotification: "Push Notification",
      level: "Notification Level",
      settings: "EkosLive Pro Settings"
  }
};

export default cn;
