const cn = {
    "general": {
       "home": "Home",
       "next": "Next",
       "ok": "确认",
       "done": "Done",
       "cancel": "取消",
       "apply": "应用",
       "save": "保存",
       "select": "Select",
       "connect": "连接",
       "disconnect": "断开",
       "yes": "是",
       "no": "否",
       "error": "Error",
       "back": "返回",
       "delete": "删除",
       "remove": "移除",
       "online": "在线",
       "offline": "离线",
       "remote": "遥控",
       "preset": "Preset",
       "camera": "相机",
       "focuser": "Focuser",
       "filter_wheel": "滤镜轮",
       "filter": "滤镜",
       "exposure": "曝光",
       "binning": "像素合并",
       "action": "动作",
       "scope_type": "望远镜类型",
       "solver_type": "解析类型",
       "type": "类型",
       "gain": "Gain",
       "offset": "Offset",
       "format": "Format",
       "iso": "ISO",
       "count": "连拍",
       "delay": "延时",
       "status": "状态",
       "target": "目标",
       "angle": "Angle",
       "sep_profile": "SEP Profile",
       "direction": "Direction",
       "rotation": "Rotation",
       "automatic": "Automatic",
       "manual": "Manual",
       "azimuth": "方位角",
       "altitude": "高度角",
       "tags": "标签",
       "filename": "文件名",
       "size": "尺寸",
       "frame": "画幅",
       "temperature": "温度",
       "name": "名称",
       "date": "日期",
       "resolution": "Resolution",
       "select_option": "请选择...",
       "search": "查找...",
       "no_results": "无结果",
       "on": "开",
       "off": "关",
       "go": "前往",
       "add": "添加",
       "edit": "编辑",
       "refresh": "刷新",
       "reset": "重置",
       "reset_all": "Reset All",
       "start": "开始",
       "stop": "停止",
       "stopping": "Stopping",
       "clear": "清除",
       "solve": "解析",
       "parked": "复位",
       "unparked": "取消复位",
       "open": "Open",
       "closed": "Close(d)",
       "enable": "Enable",
       "disable": "Disable",
       "selectTime": "Select Time",
       "set": "Set",

       // Confirm Delete Alert
       "alert_confirm_delete_title": "Confirm Delete",
       "alert_delete_profile_body": "Are you sure you want to delete the selected profile?",
       "alert_delete_scope_body": "Are you sure you want to delete the selected scope?",

       "network_error": "请确认StellarMate已联网",
       "internet_required": "Please make sure that you are connected to the internet",
       "alert_comm_error_title": "Communication Error",
       "alert_comm_error_body": "Failed to communicate with StellarMate. Please make sure it is connected to your network.",
       "ekoslive_down_title": "EkosLive is down",
       "ekoslive_down_body": "EkosLive is not running, try rebooting StellarMate or contact StellarMate support.",
       "kstars_down_title": "KStars is down",
       "kstars_down_body": "KStars is not running, try rebooting StellarMate or contact StellarMate support.",
       "reset_default": "Reset to default",
       "external_storage": "External Storage"
    },
    "darkLibrary":{
      "title": "Dark Library",
      "darks": "Darks",
      "defects": "Defects",
      "prefer": "Prefer",
      "create_darks_title": "Create Darks",
      "create_defects_title": "Create Defect Map",
      "view_masters_title": "View Masters",
      "progress": "Progress",

      "create_darks":{
          "exposure_range": "Exp. Range",
          "to": "To",
          "temp_range": "T. Range",
          "binning": "Binning",
          "binningOne": "1x1",
          "binningTwo": "2x2",
          "binningFour": "4x4",
          "total_images": "Total",
          "count": "Count"

      },

      "create_defect_map":{
          "master_dark": "Master Dark",
          "temperature": "Temperature",
          "bad_pixels": "Bad Pixels",
          "hot_pixels": "Hot Pixels",
          "generate_map": "Generate Map",
          "save_map": "Saved",
          "deviation": "σ"
      },
      
  },
    "splash": {
       "checking_for_updates": "检测更新中...",
       "downloading_package": "下载更新中...",
       "installing_update": "安装更新包...",
       "channel_update": "Channel switching in progress...",
       "upto_date": "已是最新版本",
       "update_installed": "更新已安装",
       "loading": "加载中..."
    },
    "validations": {
       "username_required": "请输入用户名",
       "username_tooshort": "至少需要3个字母",
       "username_toolong": "不能超过64个字母",
       "username_invalid": "用户名含有非法字符",
       "password_required": "请输入密码",
       "password_invalid": "至少需要6位",
       "confirm_password_required": "请确认密码",
       "confirm_password_mismatch": "密码错误",
       "email_required": "请填写邮箱",
       "email_invalid": "邮箱地址无效",
       "license_required": "请输入许可证密钥",
       "serial_required": "请输入序列号",
       "new_scope_vendor": "Enter a valid vendor name",
       "new_scope_model_invalid": "Enter a valid model",
       "new_scope_aperture_invalid": "Enter a valid aperture",
       "new_scope_focal_length_invalid": "Enter a valid focal length"
    },
    "progress": {
       "please_wait": "请稍候 ...",
       "establishing_connection": "正在建立连接",
       "cameras": "获取相机",
       "mounts": "获取赤道仪",
       "scopes": "获取望远镜",
       "filter_wheels": "获取滤镜轮",
       "registering": "Registering...",
       "registered": "Registered",
       "authenticating": "Authenticating...",
       "authenticated": "Authenticated",
       "checking_kstars": "Checking KStars...",
       "kstars_open": "KStars Open",
       "checking_ekoslive": "Checking EkosLive...",
       "ekoslive_connected": "EkosLive Connected",
       "starting_ekos": "Starting Ekos...",
       "getting_devices": "Getting Devices...",
       "loading_settings": "Loading Settings..."
    },
    "welcome": {
       "register_new_device": "Register new device?",
       "have_existing_account": "Have an existing account?",
       "require_sm_plus_pro": "Register if you have"
    },
    "device_scanner": {
       "scanning": "正在联网获取StellarMate设备中，请稍侯",
       "qr_scan": "Scan your Device QR Code"
    },
    "statuses": {
       "Idle": "闲置",
       "Aborted": "中断",
       "Calibration error": "校准错误",
       "Capturing": "正在捕获",
       "In Progress": "进行中",
       "Setting Temperature": "设置温度",
       "Slewing": "反转中",
       "Calibrating": "校准中",
       "Tracking": "追踪中",
       "Guiding": "导星中",
       "Parking": "复位中",
       "User Input": "请输入",
       "Complete": "完成",
       "Suspended": "暂停",
       "Parked": "复位"
    },
    "connect": {
       "heading": "连接",
       "register_welcome": "Please sign in to your stellarmate.com account to synchronize devices.",
       "welcome_heading": "欢迎使用",
       "welcome_description": "请确认您已连接至StellarMate的热点或StellarMate与您的设备处于同一网络中",
       "welcome_rescan": "Click RESCAN to begin scanning the network for StellarMate devices.",
       "device_unreachable": "设备无法访问！ 请检查电源和网络设置",
       "login_mismatch": "认证失败。App 密码与stellarmate.com上设定的密码不一致。请使用正确密码再次登入。",
       "old_stellarmate_heading": "版本过旧。请更新!",
       "old_stellarmate_description": "您正在使用 StellarMate OS 的旧版本。若想继续使用本应用，请务必更新至  StellarMate 的最新版本。",
       "primary": "主镜",
       "guide": "导星相机",
       "scope": "导星镜",
       "btn_rescan": "重新扫描",
       "btn_port_select": "Port Selector",
       "btn_sync_gps": "同步GPS",
       "btn_dslr_setup": "相机设置",
       "btn_clear_driver_config": "Clear Driver Config.",
       "scan_in_progress": "正在扫描 ...",
       "connection_in_progress": "正在连接StellarMate...",
       "registration_in_progress": "Registering StellarMate...",
       "logging_in_progress": "Logging to StellarMate...",
       "connecting": "Connecting...",
       "registering": "Registering...",
       "logging": "Logging...",
       "ip_address": "请输入IP地址",
       "login_register": {
          "heading": "认证",
          "heading_online": "Sign in to stellarmate.com",
          "connect_to_internet": "You must be connected to the Internet.",
          "connect_to_sync": "This is only done once to synchronize your account.",
          "reset_app": "Tip: You can resynchronize the app with your online account by going to the About tab and clicking Reset App button then re-launching the app",
          "no_valid_device": "无有效的设备信息",
          "setup_guide": "设置导星设备",
          "register": "注册",
          "login": "登入",
          "serial": "序列号#",
          "license": "许可证密钥",
          "username": "用户名",
          "password": "密码",
          "confirm_password": "确认密码",
          "first_name": "First name",
          "last_name": "Last name",
          "email": "Email"
       },
       "device_manager": {
          "alert_confirm_remove_title": "确认移除",
          "alert_confirm_remove_body": "确定移除该设备？",
          "btn_sign_out": "登出"
       },
       "profile_manager": {
          "heading": "配置文件"
       },
       "port_selector": {
          "port_selector": "Port Selector",
          "connect_all": "Connect All"
       },
       "manually_add_device": {
          "heading": "手动添加设备",
          "btn_add_device": "添加设备",
          "alert_unreachable_title": "发生错误",
          "alert_unreachable_body": "尝试在指定的IP地址处寻找设备时出错，请检查IP地址，然后重试"
       },
       "device_scanner": {
          "no_device_before_scan": "未检测到设备，请运行扫描程序",
          "no_device_after_scan": "扫描完成，未发现设备",
          "progress": "进度",
          "auto_scanned": "自动扫描",
          "manually_added": "手动添加",
          "add_a_device": "添加设备",
          "devices_detected": "检测完毕",
          "no_network_found": "No network detected. Make sure you are connect to a network."
       },
       "add_profile": {
          "add_profile": "添加配置文件",
          "edit_profile": "编辑配置文件",
          "mount": "赤道仪",
          "ccd": "主相机",
          "guider": "导星器",
          "focuser": "调焦器",
          "filter": "滤镜",
          "ao": "自适应光学设备",
          "dome": "圆顶",
          "weather": "天气设备",
          "aux1": "辅助设备1",
          "aux2": "辅助设备2",
          "aux3": "辅助设备3",
          "aux4": "辅助设备4"
       },
       "add_scope": {
          "add_scope": "添加望远镜",
          "edit_scope": "编辑望远镜",
          "vendor": "厂商",
          "model": "型号",
          "aperture": "口径 (mm)",
          "focal_length": "焦距 (mm)"
       },
       "auto_detect": {
          "alert_auto_detect_title": "Auto Detect Instructions",
          "alert_auto_detect_body": "Unplug ALL equipment from StellarMate then press Ok. Then plug them one by one to detect the device type and driver. After each device is plugged, you need to confirm the driver.",
          "alert_mapped_title": "Device Mapping",
          "alert_mapped_body": "Device serial port is successfully mapped.",
          "alert_missing_driver_title": "Driver missing",
          "alert_missing_driver_body": "You must select a driver first."
       },
       "dslr_setup": {
          "heading": "相机设置",
          "width": "宽",
          "height": "高",
          "pixel_width": "像素宽",
          "pixel_height": "像素高"
       }
    },
    "targets": {
       "now": "Now",
       "night": "Night",
       "rise": "Rise",
       "set": "Set",
       "moon": "Moon",
       "sun": "Sun",
       "search": "Search",
       "phases": {
          "new_moon": "New Moon",
          "full_moon": "Full Moon",
          "first_quarter": "First quarter",
          "third_quarter": "Third quarter",
          "waxing_crescent": "Waxing crescent",
          "waxing_gibbous": "Waxing gibbous",
          "waning_crescent": "Waning crescent",
          "waning_gibbous": "Waning gibbous"
       },
       "lists": "Lists",
       "framing_assistant": "Framing Assistant",
       "target_rotation": "Target Rotation",
       "current_rotation": "Current Rotation",
       "rotate_capture": "Rotate & Capture",
       "angular_offset": "Angular Offset",
       no_objects_in_list: "No Objects found, please adjust or reset the filters.",
       "go_and_solve": "Go & Solve",
       "fov_profile": "FOV Profile",
       "fov_width": "FOV Width",
       "fov_height": "FOV Height"
    },
    "ekos": {
       "heading": "Ekos",
       "tgl_mount": "赤道仪",
       "tgl_solution_bar": "状态栏",
       "tgl_sequence": "拍摄队列",
       "tgl_properties": "属性",
       "alert_ekos_offline_title": "Ekos离线中",
       "alert_ekos_offline_body": "Ekos目前处于离线状态，是否开启设备匹配?",
       "ekos_dialog": {
          "heading": "Ekos",
          "auto_closes_in": "Auto closes in"
       },
       "controls_bar": {
          "mount_speed": "赤道仪转速",
          "guide": "导星",
          "centering": "居中",
          "find": "寻找",
          "max": "最大"
       },
       "collapse_align": {
          "heading": "导星",
          "action_sync": "同步",
          "action_slew": "回转至目标",
          "action_nothing": "不进行动作",
          "scope_primary": "主镜",
          "scope_guide": "导星镜",
          "solver_backend": "Backend",
          "solver_type": "Type",
          "control": "Control",
          "solve": "Capture & Solve",
          "load": "Load & Slew",
          "polar": "Polar Align",
          "stop": "Stop",
          "scope": "Scope",
          "action": "Action",
          "accuracy": "Accuracy",
          "settle": "Settle",
          "dark": "Dark",
          "arcsec": "arcsec",
          "ms": "ms",
          "xAxis": "Iterations",
          "yAxis": "Error (arcsec)",
          "refresh_rate": "Refresh Rate"
       },
       "collapse_camera": {
          "heading": "相机设置",
          "type_light": "亮帧",
          "type_bias": "偏置",
          "type_dark": "暗场",
          "type_flat": "平场",
          "format_fits": "FITS",
          "format_native": "Native",
          "target_temp": "目标温度",
          "cooling_unavailable": "冷却不可用",
          "btn_add_to_sequence": "添加到拍摄队列",
          "btn_loop": "循环"
       },
       "capture_presets": {
          "heading": "Preset Settings"
       },
       "capture_limits": {
          "heading": "Limit Settings",
          "guiding_deviation": "Guiding Deviation <",
          "guiding_deviation_unit": "\"",
          "focusHFR": "Autofocus if HFR >",
          "focusHFR_unit": "pixels",
          "focusDeltaT": "Autofocus if ΔT° >",
          "focusDeltaT_unit": "°C",
          "refocusN": "Refocus every",
          "refocusN_unit": "minutes"
       },
       "capture_filters": {
          "heading": "Filter Settings",
          "auto_focus": "Auto Focus",
          "lock_filter": "Lock Filter"
       },
       "targets_filters": {
          "object_type": "Object Type",
          "alt": "Alt"
       },
       "capture_auto_calibration": {
          "heading": "Auto Calibration",
          "flat_source": "Flat Source",
          "flat_duration": "Flat Duration",
          "dust_builtin": "Dust Cover with Built-in Flat Light",
          "dust_external": "Dust Cover with External Flat Light",
          "wall": "Wall",
          "az": "Az",
          "alt": "Alt",
          "adu": "ADU",
          "tolerance": "Tolerance",
          "parkMount": "Park Mount",
          "parkDome": "Park Dome"
       },
       "capture_file": {
          "filename": "File Name",
          "heading": "File Settings",
          "prefix": "Prefix",
          "script": "Script",
          "directory": "Directory",
          "upload": "Save",
          "remote": "Remote",
          "filter": "Filter",
          "ts": "TS",
          "duration": "Duration"
       },
       "collapse_dome": {
          "heading": "窗口 & 圆顶",
          "cap": "窗口",
          "dome": "圆顶",
          "shutter": "Shutter",
          "domeSlaving": "Dome Slaving",
          "params": "Parameters",
          "measurements": "Measurements",
          "autosync_threshold": "Autosync Threshold (deg)",
          "radius": "Radius (m)",
          "shutter_width": "Shutter Width (m)",
          "n_displacement": "N Displacement (m)",
          "e_displacement": "E Displacement (m)",
          "up_displacement": "Up Displacement (m)",
          "ota_offset": "OTA Offset (m)"
       },
       "collapse_focus": {
          "heading": "调焦",
          "hfr": "HFR",
          "hfr_plot": "HFR图像",
          "focus_in": "In",
          "focus_out": "Out",
          "steps": "Steps",
          "start": "Start",
          "autofocus": "Auto Focus",
          "xAxis": "Steps",
          "yAxis": "HFR",
          "settings": {
             "title": "Settings",
             "suspendGuiding": "Suspend Guiding",
             "autoSelectStar": "Auto Select Star",
             "subframe": "Sub Frame",
             "fullfield": "Full Field",
             "dark": "Dark Frame",
             "box": "Box",
             "annulus": "Annulus",
             "settle": "Settle"
          },
          "process": {
             "title": "Process",
             "detection": "Detection",
             "sep_profile": "SEP Profile",
             "algorithm": "Algorithm",
             "threshold": "Threshold",
             "tolerance": "Tolerance",
             "effect": "Effect",
             "averageOver": "Average Over",
             "frames": "frames",
             "kernelSize": "Kernel Size",
             "numOfRows": "Num. of Rows",
             "sigma": "Sigma"
          },
          "mechanics": {
             "title": "Mechanics",
             "initialStepSize": "Initial Step Size",
             "maxTravel": "Max Travel",
             "maxStepSize": "Max Step Size",
             "backlash": "Backlash",
             "settle": "Settle",
             "outStepMultiple": "Out Step Multiple"
          }
       },
       "collapse_guide": {
          "heading": "导星",
          "ra_rms_plot": "赤经均方根(RMS)",
          "de_rms_plot": "赤纬均方根(RMS)",
          "total_rms_plot": "RMS",
          "scope_primary": "Primary",
          "scope_guide": "Guide",
          "scope": "Scope",
          "guidingRate": "Guiding Rate",
          "guider": "Guider",
          "via": "Via",
          "box": "Box",
          "effects": "Effects",
          "dither": "Dither",
          "pixels": "pixels",
          "frequency": "Frequency",
          "every": "every",
          "frames": "frames",
          "gpg": "GPG",
          "directions": "Directions",
          "ra": "RA",
          "dec": "DEC",
          "swap": "Swap",
          "east": "+",
          "west": "-",
          "north": "+",
          "south": "-",
          "subframe": "Subframe",
          "autostar": "Auto Star",
          "dark": "Dark",
          "aggressiveness": "Aggressiveness",
          "rarms": "RA RMS\"",
          "derms": "DE RMS\"",
          "totalrms": "Total RMS\"",
          "advanced": "Advanced",
          "clear_model": "Clear Calibration Model",
          "yAxis": "Drift (arcsec)"
       },
       "collapse_observatory": {
          "heading": "Observatory"
       },
       "collapse_polar": {
          "heading": "极轴校正",
          "mount_direction": "赤道仪导航",
          "mount_speed": "Mount Speed",
          "manual_slew": "Manual Slew",
          "west": "西",
          "east": "东",
          "mount_rotation": "赤道仪回转",
          "refresh": "刷新",
          "fov_error": "无效：视场广度必须为30角分以上",
          "polar_error": "极轴错误",
          "error": "Error: ",
          "az_error": "AZ error: ",
          "al_error": "AL error: "
       },
       "collapse_sequence": {
          "progress": "进度",
          "sequence": "队列",
          "overall_progress": "总进度",
          "sequences": "所有队列",
          "no_sequences": "无拍摄队列，您可以在相机设置中添加"
       },
       "collapse_mount": {
          "heading": "Mount",
          "tracking": "Tracking",
          "parking": "Parking",
          "meridian_flip": "Meridian Flip",
          "flip_if_ha": "Flip if HA >",
          "flip_if_ha_unit": "°",
          "pierside": "Pier Side",
          "auto_park": "Auto Park",
          "auto_park_everyday": "Every day",
          "park_at": "Park at",
          "limit_settings": "Limit Settings",
          "reset_options": "Reset Options",
          "min_alt": "Min. Alt",
          "max_alt": "Max. Alt",
          "enable_alt_limits": "Enable Alt Limits",
          "enable_ha_limits": "Enable HA Limits",
          "max_ha": "Max. HA (hours)",
          "clear_model": "Clear Model",
          "east": "E",
          "west": "W",
          "east_long": "East (pointing west)",
          "west_long": "West (pointing east)"
       },
       "modal_add_to_seq": {
          "heading": "添加到队列",
          "prefix": "前缀"
       },
       "modal_goto_sync": {
          "heading": "Goto&同步",
          "category": "星表类型",
          "j2000": "J2000",
          "btn_sync": "同步",
          "btn_goto": "Goto"
       },
       "mount_status_bar": {
          "status": "Status",
          "target": "Target",
          "ra": "RA",
          "de": "DE",
          "az": "AZ",
          "at": "AL",
          "ha": "HA"
       },
       "camera_status_bar": {
          "camera": "Camera",
          "filter": "Filter",
          "temperature": "Temperature",
          "resolution": "Resolution",
          "bin": "Bin",
          "gain": "Gain",
          "iso": "ISO",
          "offset": "Offset"
       },
       "solution_bar": {
          "ra": "赤经",
          "de": "赤纬",
          "dra": "赤经偏差",
          "dde": "赤纬偏差",
          "arcsec": "\"",
          "pix": "像素",
          "rot": "旋转角",
          "fov": "视场"
       },
       "mount_overlay": {
          "right_asc": "赤经",
          "declination": "赤纬",
          "parking": "复位中",
          "tracking": "追踪中",
          "park": "复位",
          "unpark": "取消复位"
       },
       "histogram": {
          "mean": "Mean",
          "median": "Median",
          "bit_depth": "Bit Depth",
          "non_linear_histogram": "Non-Linear Histogram"
       },
       "livestacking": {
         "auto_dark": "Auto Dark",
         "plate_solve": "Plate Solve",
         "background": "Background",
         "saturation": "Saturation",
         "contrast": "Contrast",
         "sigma_clipping": "Sigma Clipping",
         "noImages": "No Live Stacking Images found"
      }
    },
    "status": {
       "heading": "状态",
       "system": "系统",
       "info": "信息",
       "software": "软件",
       "cpu": "CPU",
       "ram": "RAM",
       "storage": "内存",
       "stable": "稳定版",
       "beta": "Beta版",
       "wifi_network": "无线网 IP",
       "hotspot_network": "热点 IP",
       "ethernet_network": "以太网 IP",
       "model": "型号",
       "version": "版本",
       "hostname": "主机名",
       "time": "时间",
       "release_type": "版本类型",
       "updates": "更新选项",
       "resolution": "协议",
       "hotspotMode": "Hotspot Mode",
       "wifiNetwork": "Wifi Network",
       "wifiBand": "WiFi Band",
       "update_available": "可用更新",
       "update_unavailable": "暂不可用更新",
       "update_in_progress": "更新中",
       "btn_vnc": "远程桌面 (VNC)",
       "btn_web_manager": "网页管理器",
       "btn_restart": "重启",
       "btn_shutdown": "关机",
       "btn_manage_wifi": "更改网络",
       "btn_enable_direct_ethernet": "启用以太网",
       "btn_disable_direct_ethernet": "禁用以太网",
       "btn_enable_hotspot": "启用热点",
       "btn_disable_hotspot": "禁用热点",
       "btn_change_hostname": "更改主机名",
       "btn_check_for_updates": "检查更新",
       "btn_update_now": "立即更新",
       "btn_update_in_progress": "更新中...",
       "btn_factory_reset": "恢复出厂设置",
       "btn_change_resolution": "变更协议",
       "btn_later": "稍后",
       "btn_resize_fs": "Resize SD",
       "btn_continue": "Continue",
       "alert_device_offline_title": "Device is offline",
       "alert_device_offline_body": "Device seems to be offline at the moment. Did you login to a device?",
       "alert_restart_title": "重启StellarMate",
       "alert_restart_body": "您的设备即将重启。重启后请尝试再次连接。",
       "alert_restart_btn_restart": "重启",
       "alert_shutdown_title": "关闭StellarMate",
       "alert_shutdown_body": "您的设备即将关闭，重新使用需要手动开启。",
       "alert_shutdown_btn_restart": "关机",
       "alert_resize_title": "Resize microSD Card",
       "alert_resize_body": "StellarMate will expand to the full SD card size. Restart StellarMate after resizing.",
       "alert_resize_btn_resize": "Resize",
       "alert_hotspot_enable_title": "启用热点",
       "alert_hotspot_enable_body": "启用热点会使StellarMate断开当前加入的wifi网络，并启动自己的热点。若继续使用StellarMate，您需要连接到此热点网络。是否继续?",
       "alert_hotspot_post_enable_title": "请连接到热点",
       "alert_hotspot_post_enable_body": "您现在可以连接到“stellarmate”热点，并在连接后点击确认以继续",
       "alert_hotspot_disable_title": "关闭热点",
       "alert_hotspot_disable_body": "禁用热点将使StellarMate连接到其先前连接过的无线网络。热点禁用时，您需要在同一网络继续使用StellarMate。是否继续?",
       "alert_factory_reset_title": "恢复出厂设置",
       "alert_factory_reset_body": "恢复出厂设置完成，请立即重启StellarMate",
       "alert_factory_reset_confirmation_body": "Are you sure you want to reset device to factory settings? All settings will be wiped. This action is irreversible!",
       "alert_forget_wifi_title": "删除Wifi",
       "alert_forget_wifi_body": "断开并删除当前Wifi将使StellarMate启用自己的热点（如果未连接到以太网）。您将需要连接到此热点才能继续使用。是否继续？",
       "alert_join_wifi_title": "加入Wifi网络",
       "alert_join_wifi_body": "加入Wifi网络将关闭StellarMate的热点（如果已启动）。若继续使用StellarMate，请确保您在同一网络上。是否继续？",
       "alert_change_resolution_title": "成功!",
       "alert_change_resolution_body": "您现在可以重启StellarMate令变更生效",
       "alert_change_release_title": "Beta Channel",
       "alert_change_release_body": "Are you sure you want to switch to the unstable and unsupported beta channel?",
       "alert_direct_ethernet_title": "Direct Ethernet",
       "alert_direct_ethernet_connect_body": "Connect Ethernet cable directly between StellarMate and your PC. Set your PC IP address to 192.168.100.2 and gateway to 192.168.100.1",
       "alert_direct_ethernet_disconnect_body": "Remove direct Ethernet cable.",
       "alert_clear_all_driver_config_title": "Clear All Driver Configuration",
       "alert_clear_all_driver_config_body": "Are you sure you want to delete all driver configuration?",
       "alert_update_complete_title": "SM OS Update",
       "alert_update_complete_body": "Update complete, please restart StellarMate.",
       "alert_network_error_title": "Network error",
       "alert_network_error_body": "Failed to query network information",
       "change_resolution_modal": {
          "heading": "变更协议",
          "mode": "模式"
       },
       "change_hostname_modal": {
          "heading": "更改主机名",
          "new_hostname": "新主机名"
       },
       "change_wifi_modal": {
          "heading": "加入网络",
          "ssid": "SSID",
          "passkey": "密码",
          "err_wifi": "搜寻Wifi时遇到了问题，请重试"
       },
       "change_band_modal": {
          "heading": "Change Band",
          "band": "Band",
          "channel": "Channel"
       },
       "vnc_view": {
          "heading": "远程桌面(VNC)",
          "alert_unreachable_title": "VNC 无法访问",
          "alert_unreachable_body": "尝试建立与VNC查看器的连接时似乎遇到了问题，请重试"
       },
       "web_manager_view": {
          "heading": "网络管理器",
          "alert_unreachable_title": "网页管理器无法访问",
          "alert_unreachable_body": "尝试建立与网页管理器的连接时似乎遇到了问题，请重试"
       }
    },
    "settings": {
       "heading": "设置",
       "general_settings": "设置",
       "language": "语言",
       "high_bandwidth": "高带宽模式",
       "transfer_images": "传输图像",
       "notifications": "通知",
       "sounds": "声音",
       "cloud_storage": "云存储",
       "auto_sync": "自动同步",
       "time": "时间",
       "location": "位置",
       "reset_app": "Reset App",
       "reset_app_body": "Purge all App settings?"
    },
    "cloud": {
       "heading": "云服务",
       "btn_filters": "筛选",
       "btn_gallery": "图库",
       "btn_info": "信息",
       "btn_offline_viewer": "Offline Viewer",
       "btn_cloud_viewer": "Cloud Viewer",
       "no_images_title": "找不到图像",
       "no_images_body": "请尝试更改筛选条件",
       "no_selected_title": "没有选择图像",
       "no_selected_body": "从图库中选择一张图片",
       "cloud_disabled_title": "云服务已禁用",
       "cloud_disabled_body": "请转到设置并启用云服务以访问此选项卡",
       "pro_plan_body": "云存储仅适用于高级用户",
       "alert_cannot_download_title": "无法下载",
       "alert_cannot_download_body": "尝试下载时出错，请重试",
       "alert_confirm_delete_title": "是否确定?",
       "alert_confirm_delete_body": "真的要删除{0}吗？删除后数据将无法恢复",
       "filters_drawer": {
          "field": "域",
          "condition": "条件",
          "value": "值",
          "btn_add_filter": "添加筛选条件",
          "airmass": "大气光学质量",
          "mount": "赤道仪",
          "object": "对象",
          "contains": "包含"
       },
       "gallery_drawer": {
          "all": "全部",
          "h1": "1h",
          "h24": "1d",
          "d7": "7d",
          "m1": "1m",
          "y1": "1y",
          "images": "图像",
          "btn_sort": "分类",
          "btn_delete_all": "全部删除",
          "ascending": "升序",
          "descending": "降序",
          "alert_no_images_title": "无图像",
          "alert_no_images_body": "没有可以删除的图像",
          "alert_delete_all_title": "是否确定?",
          "alert_delete_all_body": "确定删除选定的 {0} 张图片吗? 此操作无法恢复"
       },
       "info_drawer": {
          "add_tags_here": "在这里添加标签",
          "captured_on": "已捕获"
       }
    },
    "about": {
       "heading": "关于",
       "version": "版本",
       "bundle": "Bundle",
       "copyright_line1": "StellarMate is developed by Ikarus Technologies ? 2017-2021",
       "copyright_line2": "Background image by Alamri Observatory"
    },
    "messages": {
       "polar_idle": "This tool provides a simple method to polar align a German equatorial mount. Park your mount to home position where it points toward the celestial pole with the counter weight down. Select mount direction and speed and then click Start to begin the process. If you do not have a view of the pole, use the SkyMap or Ekos mount control to point anywhere, preferably near the meridian, choose East or West according your side, lower the rotation angle if necessary, and click Start."
    }
 };

export default cn;
