const fr = {
    "general": {
        "home": "Accueil",
        "next": "prochain",
        "ok": "D'accord",
        "done": "Fait",
        "cancel": "Annuler",
        "apply": "Appliquer",
        "save": "sauvegarder",
        "select": "Sélectionner",
        "connect": "Connecter",
        "disconnect": "Déconnecter",
        "yes": "Oui",
        "no": "Non",
        "error": "Erreur",
        "back": "Retour",
        "delete": "Supprimer",
        "remove": "Retirer",
        "online": "En ligne",
        "offline": "Hors ligne",
        "cloud": "Cloud",
        "remote": "Distant",
        "preset": "Préréglage",
        "camera": "Caméra",
        "focuser": "Focuser",
        "filter_wheel": "Roue à filtre",
        "filter": "Filtre",
        "exposure": "Exposition",
        "binning": "Binning",
        "action": "Action",
        "scope_type": "Type de Tube",
        "solver_type": "Type de solveur",
        "type": "Type",
        "gain": "Gain",
        "offset": "Décalage",
        "format": "Format",
        "iso": "ISO",
        "count": "Nombre",
        "delay": "Retard",
        "status": "Statut",
        "target": "Cible",
        "angle": "Angle",
        "sep_profile": "Profil SEP",
        "direction": "Direction",
        "rotation": "Rotation",
        "automatic": "Automatique",
        "manual": "Manuel",
        "progress": "Progression",
        position_angle: "PA",
        details: "Details",
        skip: "Skip",
        updated: "Updated",
        new: "New",

        "azimuth": "Azimut",
        "altitude": "Altitude",
        "tags": "Mots clés",
        "filename": "Nom du fichier",
        "size": "Taille",
        "frame": "Cadre",
        "temperature": "Température",
        "name": "Nom",
        "date": "Date",
        "resolution": "Résolution",

        "selectFile": "Select file",
        "selectFolder": "Select folder",
        "selectedDir": "selected folder",
        "new_folder": "Enter new folder name",
        "create_new_folder": "Create new folder in",
        "empty_folder": "Folder is Empty",

        "train": "Train",
        "no_data_found": "No data found",
        "track": "Track",
        "jobs": "Jobs",
        "category": "Categories",
        "profile": "Profile",
        "arcmin": "arcmin",
        "calculate": "Calculate",
        "update": "Update",
        "center": "Center",
        "learnMore": "Learn more",

        "select_option": "Sélectionnez l'option...",
        "search": "Chercher...",
        "no_results": "Aucun résultat",
        "on": "Marche",
        "off": "Arrêt",
        "go": "ALLER",
        "add": "AJOUTER",
        "edit": "ÉDITER",
        "refresh": "Rafraichir",
        "reset": "Réinitialiser",
        "reset_all": "Tout réinitialiser",
        "start": "Début",
        "stop": "Arrêtez",
        "stopping": "Arrêt",
        "clear": "Effacer",
        "solve": "Résoudre",
        "parked": "Parquée",
        "unparked": "Dé Parquée",
        "open": "Ouvrir",
        "close": "Fermé",
        "opened": "Ouvrir",
        "closed": "Fermé",
        "enable": "Activer",
        "disable": "Désactiver",
        "selectTime": "Durée",
        "set": "Définir",

        // Confirm Delete Alert
        "alert_confirm_delete_title": "Confirmer Suppression",
        "alert_delete_profile_body": "Voulez-vous vraiment supprimer le profil sélectionné ?",
        "alert_delete_scope_body": "Êtes-vous sûr de vouloir supprimer le scope sélectionné?",

        // Confirm
        "alert_confirmation_title": "Confirmation",
        "alert_create_preset_body": "Are you sure you want to create preset with this name?",

        "network_error": "Veuillez vous assurer que votre StellarMate est connecté à votre réseau",
        "internet_required": "Veuillez vous assurer que vous êtes connecté à Internet",
        "alert_comm_error_title": "Erreur de communication",
        "alert_comm_error_body": "Échec de la communication avec StellarMate. Veuillez vous assurer qu'il est connecté à votre réseau.",
        "ekoslive_down_title": "EkosLive est en panne",
        "ekoslive_down_body": "EkosLive n'est pas en cours d'exécution, essayez de redémarrer StellarMate ou contactez l'assistance StellarMate.",
        "kstars_down_title": "KStars est en panne",
        "kstars_down_body": "KStars n'est pas en cours d'exécution, essayez de redémarrer StellarMate ou contactez le support StellarMate.",
        "reset_default": "Reset to default",
        "external_storage": "Stokage Externe"
    },
    "darkLibrary": {
        "title": "Dark Library",
        "darks": "Darks",
        "defects": "Defects",
        "prefer": "Prefer",
        "create_darks_title": "Créer Darks",
        "create_defects_title": "Créer la Defect Map",
        "view_masters_title": "View Masters",
        "progress": "Progression",

        "create_darks": {
            "exposure_range": "Plage d'expo.",
            "to": "à",
            "temp_range": "Plage de temp.",
            "binning": "Binning",
            "binningOne": "1x1",
            "binningTwo": "2x2",
            "binningFour": "4x4",
            "total_images": "Total",
        },

        "create_defect_map": {
            "master_dark": "Master Dark",
            "bad_pixels": "Bad Pixels",
            "hot_pixels": "Pixels chauds",
            "generate_map": "Generer carte",
            "save_map": "Sauvegardé",
            "deviation": "σ"
        },
    },
    achievements:{
        score: "Total Score",
        badge: "Badge",
        achievements: "Achievements",
        unlocked: "Achievement Unlocked",
        points: "Points",
        completed: "Completed",
        notCompleted: "Not completed",
        capture_preview_title: "First Light!",
        ten_sequences_title: "So it begins!",
        mount_goto_title: "Magic Fingers",
        video_recording_title: "Director’s Cut",
        weather_check_title: "Cloud Magnet",
        live_stacking_title: "Let there be details",
        create_darks_title: "Embrace the dark side",
        create_defect_title: "Cosmic Makeup",
        import_mosaic_title: "Mosaic Weaver", 
        messier_captured_title: "MXXXX (e.g. M1)",
        all_messier_title: "Cosmic Marathon",
        scheduler_title: "Robotic Master", 
        capture_master_title: "Sky Master",
        capture_legend_title: "Sky Legend",
        paa_title: "Perfectionist",
        guide_rms_title: "Bullseye!",

        capture_preview_description: "Capture a Preview",
        ten_sequences_description: "Capture a sequence with 10 counts",
        mount_goto__description:  "Use Target GOTO by holding on the object for 3 seconds when the new image is captured",
        video_recording_description: "Record video for 1 minute",
        weather_check__description: "Use Cloud Map in weather info, Zoom in to at least 8x to check weather",
        live_stacking_description:  "Live stacking. Perform at least 5 images",
        create_darks_description:  "Create Darks of total 50 Images",
        create_defect_description: "Generate hot / cold pixels in Defect map above 80",
        import_mosaic_description: "Import Mosaics from telescopios",
        messier_captured_description: "A messier object is captured",
        all_messier_description: "All Messier objects were captured",
        scheduler_description: "Finish a scheduler job worth 2 or more hours of image data.",
        capture_master_description: "Capture a total of 500 images",
        capture_legend_description: "Capture a total of 1000 images",
        paa_description: "Finish PAA with box error lower than 30 arcsecs.",
        guide_rms_description: "Achieve total RMS guiding below 0.5 arcsecs.",
    },
    tourGuide:
    {
      tour_guide: "Tour Guide",
      previous: "Previous",
      finish: "Finish",
      title_devices_list: "StellarMate Devices List",
      title_device_actions: "Device Actions",
      title_profles: "Profiles",
      title_port_selector: "Port Selector",
      title_trains: "Optical trains",
      title_weather_bar: "Weather bar",
      title_cloud_report: "Cloud Report",
      title_next: "What's next?",

      title_focus: "Focus",
      title_align: "Align",
      title_guide: "Guide",
      title_capture: "Capture",
      title_mount: "Mount",
      title_observatory: "Observatory",
      title_scheduler: "Scheduler",
      title_indi: "INDI Control Panel",
      title_quick_controls: "Quick Controls",
      title_preview: "Preview",
      title_framing: "Framing",
      title_live_video: "Live Video",
      title_stop: "Stop",
      title_live_stacking: "Live Stacking",
      title_quick_settings: "Qucik Camera Settings",
      
      title_targets_info: "About Targets",
      title_search_bar: "Search bar",
      title_time_controls: "Time Controls",
      title_target_controls: "Targets Controls",
      title_object_info: "Object info",
      title_fov: "Target Field Of View",
      title_target_action: "Target Action",

      description_devices_list: "This is the list of automatically discovered and manually added StellarMate units. Tap RESCAN to detect new StellarMate units on the network.",
      description_device_actions: "Remove a device from the list, perform a factory reset, or log out.",
      description_profles: "Manage your astronomy equipment in Equipment Profiles. All equipment must be powered and connected to StellarMate before starting a profile. Once a profile is started, configure the Optical Trains and then tap Ekos to start your astrophotography session.",
      description_port_selector: "After a profile is started for the first time, select the serial and/or network settings for your devices.",
      description_trains:
      "Set up how your equipment is arranged using Optical trains. Assign each device to a specific function. Create a train for each camera.",
      description_weather_bar:"Brief weather report and current site Bortle class",
      description_cloud_report: "3-hours Cloud overlay." , 
      description_next: "Explore applicable astronomical targets by tapping the Targets tab. Use Go & Solve to center your target in the camera frame. Open the Framing Assistant to achieve the perfect desired orientation. Head over to Ekos tab to set up imaging sequences and live stack images.", 

      description_focus: "Focus the camera by using a motorized focuser.",
      description_align: "Center the mount exactly on target by plate-solving an image.",
      description_guide: "Keep the mount locked to your target during tracking to enable long exposures.",
      description_capture: "Create sequences to capture images using configurable settings. Manage filter wheel settings and Dark Library.",
      description_mount: "Toggle tracking, parking, and meridian flip settings. Configure auto-park.",
      description_observatory: "Control dome and dust-cap equipment.",
      description_scheduler: "Automate complete astrophotography session by selecting target and sequence file. Import mosaics from Telescopius.",
      description_indi: "Direct low-level access to equipment properties.",
      description_quick_controls: "Quick access to mount, camera, and rotator controls.",
      description_preview: "Capture a single preview frame.",
      description_framing: "Loop exposures indefinitely until stopped",
      description_live_video: "Start live video streams and record videos to storage.",
      description_stop: "Stop any ongoing exposures or recordings.",
      description_live_stacking: "Live stack images to increase signal to noise ratio. If an existing capture sequence is running, live stacking will use incoming images otherwise it will loop exposures using settings in Quick Camera Settings.",
      description_quick_settings: "Select active train and configure camera and filter wheel settings.",
      
      description_targets_info: "Targets is the StellarMate Planning tool to streamline your observation session. Search from thousands of objects and filter them using simple criteria. Use the Framing Assistant to frame your targets." ,
      description_search_bar:
        "Filter objects in the existing list or search for new objects by entering the name and tapping the search button.",
      description_time_controls:
        "If Ekos is offline, adjust the target date and time calculations.",
      description_target_controls:
        "Check out twilight information, manage FOVs, adjust filters, and select object types.",
      description_object_info: "Object magnitude, rise, transit, and set times.",
      description_fov: "Tap to enter Framing Assistant mode.",
      description_target_action: "Add target to favorites or custom list. Command a GOTO only or a GOTO followed by capture and solve. If Ekos is offline, schedule the target.",
    },
    tooltip: 
    {
        placeholder: "Placeholder %{0} or %{1}",
        placeholder_file: "The name of the .esq file, without extension.",
        placeholder_date: "The current time and date when the file is saved.",
        placeholder_type: "The frame type e.g: 'Light', 'Dark'",
        placeholder_exp: "The exposure duration in seconds.",
        placeholder_filter: "The active filter name.",
        placeholder_seq: "The image sequence identifier where * is the number of digits used (1-9), This tag is mandatory and must be the last element in the format",
        placeholder_target: "The Target name.",
        format_title: "Format is used to define the image file names by the use of placeholder tags.",
        suffix: "Number of digits used to append the sequence number to the filename",
        paa_desc: "Use plate-solving method for Polar Alignment. Plate solving is slower but provides more accurate results.",
        plate_solving: "Uses plate solving to track what the corrected alignment error is during the Refresh process. User should try to reduce the error in the Updated Err line below and minimize the size of the arrows.",
        movestar_title:"Move Star and Calc Error",
        movestar_desc: "Like Move Star, But Ekos attemps to track the star being moved and estimates the current alignment error when it can."
    },
    "splash": {
        "checking_for_updates": "Vérification des mises à jour...",
        "downloading_package": "Téléchargement de la mise à jour...",
        "installing_update": "Installation de mise à jour...",
        "channel_update": "Changement de canal en cours...",
        "upto_date": "Déjà à jour.",
        "update_installed": "Toutes les mises à jour installées.",
        "loading": "Chargement..."
    },
    "validations": {
        "username_required": "Le nom d'utilisateur est obligatoire",
        "username_tooshort": "Minimum 3 caractères requis",
        "username_toolong": "Ne peut pas contenir plus de 64 caractères",
        "username_invalid": "Caractères non valides dans le nom d'utilisateur",
        "password_required": "Mot de passe requis",
        "password_invalid": "Minimum 6 caractères requis",
        "confirm_password_required": "Confirmer le mot de passe requis",
        "confirm_password_mismatch": "Confirmer le mot de passe incorrect",
        "email_required": "Email (requis",
        "email_invalid": "Adresse e-mail invalide",
        "license_required": "Clé de licence requise",
        "serial_required": "Clé de série requise",
        "new_scope_vendor": "Entre un nom de fournisseur valide",
        "new_scope_model_invalid": "Entre un modèle valide",
        "new_scope_aperture_invalid": "Entre une ouverture valide",
        "new_scope_focal_length_invalid": "Entre une focale valide",
        "new_scope_focal_ratio_invalid": "Enter a valid focal ratio",

    },
    "progress": {
        "please_wait": "S'il vous plaît, attendez ...",
        "establishing_connection": "Établissement de la connexion",
        "cameras": "Obtenir des caméras",
        "mounts": "Obtenir des montures",
        "scopes": "Obtenir des Télescopes",
        "filter_wheels": "Obtenir des roues de filtre",
        "registering": "Enregistrement...",
        "registered": "inscrit",
        "authenticating": "Authentification...",
        "authenticated": "Authentifié",
        "checking_kstars": "Vérification de KStars...",
        "kstars_open": "KStars ouvert",
        "checking_ekoslive": "Vérification d'EkosLive...",
        "ekoslive_connected": "EkosLive connecté",
        "starting_ekos": "Démarrer Ekos...",
        "getting_devices": "Obtenir des appareils...",
        "loading_settings": "Chargement des paramètres...",
        register_device: "Scanned QR Code, Registering Device: ",
    },
    "welcome": {
        "register_new_device": "Enregistrer un nouvel appareil?",
        "have_existing_account": "Vous avez un compte existant?",
        "require_sm_plus_pro": "Inscrivez-vous si vous avez"
    },
    "device_scanner": {
        "scanning": "Veuillez patienter pendant que nous recherchons des appareils StellarMate sur le réseau",
        "qr_scan": "Scannez le QR Code de votre appareil "
    },
    "statuses": {
        "Idle": "Inactif",
        "prep": "Prep",
        "run": "Run",
        "Aborted": "Avorté",
        "Calibration error": "Erreur d'étalonnage",
        "Capturing": "Capturer",
        "In Progress": "En cours",
        "Setting Temperature": "Réglage de la température",
        "Slewing": "Pivotement",
        "Calibrating": "Étalonnage",
        "Tracking": "Poursuite",
        "Guiding": "Guidage",
        "Parking": "Parking",
        "User Input": "Entrée utilisateur",
        "Complete": "Compléter",
        "Suspended": "Suspendu",
        "Parked": "Parquée"
    },
    "connect": {
        "register_welcome": "Veuillez vous connecter à votre compte stellarmate.com pour synchroniser les appareils.",
        "welcome_heading": "Salut!",
        "welcome_description": "Veuillez vous assurer que vous êtes connecté au HotSpot de StellarMate ou que StellarMate est sur le même réseau que vous.",
        "welcome_rescan": "Cliquez sur RESCAN pour commencer à scanner le réseau pour les appareils StellarMate.",
        "device_unreachable": "L'appareil n'est pas accessible! Vérifiez les paramètres d'alimentation et de réseau.",
        "login_mismatch": "Authentification échouée. Le mot de passe de l'application est différent du mot de passe en ligne de stellarmate.com. Enregistrez à nouveau l'application avec le mot de passe en ligne correct.",
        "old_stellarmate_heading": "Mise à jour requise!",
        "old_stellarmate_description": "Vous semblez utiliser une ancienne version de StellarMate OS. Vous devez passer à la version la plus récente de StellarMate pour continuer à utiliser cette application.",
        "primary": "Primaire",
        "guide": "Guider",
        "scope": "Portée",
        "btn_rescan": "RESCAN",
        "btn_port_select": "Selection de port",
        "btn_sync_gps": "Synchroniser le GPS",
        "btn_dslr_setup": "Configuration DSLR",
        "btn_clear_driver_config": "Effacer la configuration du pilote.",
        "scan_in_progress": "Analyse en cours ...",
        "connection_in_progress": "Connexion de StellarMate ...",
        "registration_in_progress": "Enregistrement de StellarMate ...",
        "logging_in_progress": "Connexion à StellarMate ...",
        "generic": "Generic Serial",
        "select_driver": "Please select device type and driver",

        "connecting": "De liaison...",
        "logging": "Enregistrement...",
        "ip_address": "Adresse IP",
        "login_register": {
            "heading": "Authentifier",
            "heading_online": "Connectez-vous à stellarmate.com",
            "connect_to_internet": "Vous devez être connecté à Internet.",
            "connect_to_sync": "Cela n'est fait qu'une seule fois pour synchroniser votre compte.",
            "reset_app": "Conseil: vous pouvez resynchroniser l'application avec votre compte en ligne en accédant à l'onglet À propos et en cliquant sur Bouton de réinitialisation de l'application, puis relance de l'application",
            "no_valid_device": "Aucune information valide sur l'appareil disponible.",
            "setup_guide": "Guide d'installation",
            "register": "S'inscrire",
            "login": "Se connecter",
            "serial": "Numéro de série",
            "license": "Clé de licence",
            "username": "Nom d'utilisateur",
            "password": "Mot de passe",
            "confirm_password": "Confirmez le mot de passe",
            "first_name": "Prénom",
            "last_name": "Nom",
            "email": "Email"
        },
        "device_manager": {
            "alert_confirm_remove_title": "Confirmer la suppression",
            "alert_confirm_remove_body": "Voulez-vous vraiment supprimer cet appareil?",
            "btn_sign_out": "Déconnexion"
        },
        "profile_manager": {
            "heading": "Profils d'équipement"
        },
        "port_selector": {
            "connect_all": "Tout connecter"
        },
        "manually_add_device": {
            "heading": "Ajouter manuellement un appareil",
            "btn_add_device": "Ajouter un appareil",
            "alert_unreachable_title": "Une erreur s'est produite",
            "alert_unreachable_body": "Une erreur s'est produite lors de la tentative de localisation du périphérique à l'adresse IP spécifiée. Veuillez vérifier à nouveau l'adresse IP et réessayer."
        },
        "device_scanner": {
            "no_device_before_scan": "Aucun appareil détecté. Exécutez le scanner.",
            "no_device_after_scan": "Analyse terminée. Aucun périphérique trouvé.",
            "auto_scanned": "Analyse automatique",
            "manually_added": "Ajouté manuellement",
            "add_a_device": "Ajouter un périphérique",
            "devices_detected": "Appareil détecté",
            "no_network_found": "Aucun réseau détecté. Assurez-vous que vous êtes connecté à un réseau."
        },
        "add_profile": {
            "add_profile": "Ajouter un profil",
            "edit_profile": "Editer le profil",
            "mount": "Monture",
            "ccd": "Camera 1",
            "dome": "Dome",
            "guider": "Camera 2",
            "ao": "Optique adaptative",
            "weather": "Météo",
            "aux1": "Aux1",
            "aux2": "Aux2",
            "aux3": "Aux3",
            "aux4": "Aux4"
        },
        "add_scope": {
            "add_scope": "Ajouter un télescope",
            "edit_scope": "Modifier le télescope",
            "vendor": "Fabricant",
            "aperture": "Ouverture (mm)",
            "focal_length": "Focale (mm)"
        },
        "auto_detect": {
            "alert_auto_detect_title": "Instructions de détection automatique",
            "alert_auto_detect_body": "Débranchez TOUS les équipements de StellarMate puis appuyez sur Ok. Puis branchez-les un par un pour détecter le type de périphérique et le pilote. Une fois que chaque périphérique est branché, vous devez confirmer le pilote.",
            "alert_mapped_title": "Cartographie des appareils",
            "alert_mapped_body": "Le port série de l'appareil est correctement mappé.",
            "alert_missing_driver_title": "Pilote manquant",
            "alert_missing_driver_body": "Vous devez d'abord sélectionner un pilote."
        },
        "dslr_setup": {
            "width": "Largeur",
            "height": "la taille",
            "pixel_width": "Largeur pixel",
            "pixel_height": "Hauteur pixel"
        }
    },
    "targets": {
        "now": "Maintenant",
        "night": "Nuit",
        "rise": "Lever",
        "moon": "Lune",
        "sun": "Soleil",
        "search": "Chercher",
        "cam_width": "Camera Width",
        "cam_height": "Camera Height",
        "phases": {
            "new_moon": "Nouvelle Lune",
            "full_moon": "Pleine Lune",
            "first_quarter": "Premier Quartier",
            "third_quarter": "Dernier Quartier",
            "waxing_crescent": "Premier croissant",
            "waxing_gibbous": "Gibbeuse croissante",
            "waning_crescent": "Dernier croissant",
            "waning_gibbous": "Gibbeuse décroissante"
        },
        "lists": "Liste",
        "framing_assistant": "Framing Assistant",
        "target_rotation": "Target Position Angle",
        "current_rotation": "Current Rotation",
        "rotate_capture": "Rotation & Capture",
        "goto_rotate": "GOTO & Rotation",
        "angular_offset": "Angular Offset",
        "no_objects_in_list": "Pas d'objets trouvés, ajuster ou reinitialiser les filtres.",
        "go_and_solve": "Go & Solve",
        "fov_profile": "FOV Profile",
        "fov_width": "FOV Largeur",
        "fov_height": "FOV Hauteur"
    },
    "ekos": {
        "heading": "Ekos",
        "tgl_mount": "MONTURE",
        "tgl_solution_bar": "BARRE DE SOLUTION",
        "tgl_sequence": "SÉQUENCE",
        "tgl_properties": "PROPRIÉTÉS",
        "alert_ekos_offline_title": "Ekos est hors ligne",
        "alert_ekos_offline_body": "Ekos semble être hors ligne pour le moment. Avez-vous commencé le profil d'équipement?",
        "ekos_dialog": {
            "auto_closes_in": "Fermeture automatique dans"
        },
        "controls_bar": {
            "mount_speed": "Vitesse de la monture",
            "centering": "Centrage",
            "find": "Trouver",
            "max": "Max"
        },
        "collapse_align": {
            "heading": "Aligner",
            "action_sync": "Synchroniser",
            "action_slew": "Viser vers la cible",
            "action_nothing": "Rien",
            "solver_backend": "Backend",
            "control": "Contrôle",
            "solve": "Capturer et résoudre",
            "load": "Charger et faire pivoter",
            "polar": "Alignement Polaire",
            "accuracy": "Précision",
            "settle": "Régler",
            "dark": "Dark",
            "arcsec": "arcsec",
            "ms": "SP",
            "xAxis": "Itérations",
            "yAxis": "Erreur (arcsec)",
            "refresh_rate": "Taux de rafraichissement",
            "manualRotator": {
                "heading": "Rotation Manuelle",
                "currentPA": "PA Actuel",
                "targetPA": "PA Cible",
                "another_image": "Prendre une autre Image",
            },
            "alignSettings": {
                "rotator_control": "Contôle Rotateur",
                "use_scale": "Utiliser Echelle",
                "use_position": "Utiliser Position"
            },
            "calibrationSettings": {
                "pulse": "Pulse",
                "maxMove": "Max Move",
                "twoAxis": "Two axis",
                "squareSize": "Auto square size",
                "calibrateBacklast": "Remove DEC backlash in guide calibration",
                "resetCalibration": "Reset Guide Calibration After Each Mount Slew",
                "reuseCalibration": "Store and reuse guide calibration when possible",
                "reverseCalibration": "Reverse DEC on pier-side change when reusing calibration"
            }
        },
        "collapse_camera": {
            "heading": "Capturer",
            "type_light": "Brutes",
            "type_bias": "Biais",
            "type_flat": "Flat",
            "type_dark": "Dark",
            "format_fits": "Fits",
            "format_native": "Natif",
            "cooling_unavailable": "N/A",
            "btn_add_to_sequence": "Ajouter à la séquence ",
            "btn_loop": "Boucle"
        },
        "capture_presets": {
            "heading": "Paramètres prédéfinis"
        },
        "capture_limits": {
            "heading": "Limiter les paramètres",
            "guiding_deviation": "Écart de guidage <",
            "guiding_deviation_unit": "\"",
            "focusHFR": "Autofocus si HFR>",
            "focusHFR_unit": "pixels",
            "focusDeltaT": "Autofocus si ΔT °>",
            "focusDeltaT_unit": "°C",
            "refocusN": "Recentrer chaque",
            "refocusN_unit": "minutes"
        },
        "capture_filters": {
            "heading": "Paramètres de filtre",
            "auto_focus": "Mise au point automatique",
            "lock_filter": "Verrouiller le filtre"
        },
        "targets_filters": {
            "object_type": "Type d'objet",
            "alt": "Alt"
        },
        "capture_auto_calibration": {
            "heading": "Calibration automatique",
            "flat_source": "Source de Flat",
            "flat_duration": "Durée Flat",
            "dust_builtin": "Cache-poussière avec éclairage plat intégré",
            "dust_external": "Cache-poussière avec éclairage plat externe",
            "wall": "Mur",
            "az": "Az",
            "adu": "ADU",
            "tolerance": "Tolérance",
            "parkMount": "Monture parquée",
            "parkDome": "Dôme fermé",
            "manual": "Manuel"
        },
        "capture_file": {
            "filename": "Nom du Fichier",
            "heading": "Paramètres de fichier",
            "prefix": "Préfixe",
            "script": "Scénario",
            "directory": "répertoire",
            "ts": "TS",
            "duration": "Durée",
            suffix: "Suffix",
            usb: "USB Unmounted successfully",
            unmount: "Unmount"
        },
        "collapse_dome": {
            "heading": "Coiffe et Dôme",
            "cap": "Coiffe",
            "dome": "Dôme",
            "shutter": "Obturateur",
            "domeSlaving": "Asservissement du dôme",
            "params": "Paramètres",
            "measurements": "Mesures",
            "autosync_threshold": "Seuil de synchronisation automatique (deg)",
            "radius": "Rayon (m)",
            "shutter_width": "Largeur d'obturation (m)",
            "n_displacement": "N Déplacement (m)",
            "e_displacement": "Déplacement E (m)",
            "up_displacement": "Déplacement vers le haut (m)",
            "ota_offset": "Décalage OTA (m)"
        },
        "collapse_focus": {
            "heading": "MAP-FOCUS",
            "hfr": "HFR",
            "hfr_plot": "Tracé HFR",
            "focus_in": "MAP vers l'intérieur",
            "focus_out": "MAP vers l'extérieur",
            "steps": "Pas",
            "settings": {
                "suspendGuiding": "Suspendre le guidage",
                "autoSelectStar": "Etoile selectionnée automatiquement",
                "subframe": "Sous-Trame",
                "fullfield": "Plein Champ",
                "dark": "Dark",
                "annulus": "Anneau",
            },
            "process": {
                "title": "Traiter",
                "detection": "Détection",
                "algorithm": "Algorithme",
                "threshold": "Seuil",
                "effect": "Effet",
                "averageOver": "Moyenne sur",
                "kernelSize": "Taille du noyau",
                "numOfRows": "Nombre",
                "sigma": "Sigma"
            },
            "mechanics": {
                "title": "Mécanique",
                "initialStepSize": "Taille initiale du pas",
                "maxTravel": "Trajet maximum",
                "maxStepSize": "Taille maximale du pas",
                "backlash": "Backlash",
                "outStepMultiple": "délai déplacement dépassé"
            }
        },
        "collapse_guide": {
            "total_rms_plot": "RMS",
            "scope_primary": "Primaire",
            "guidingRate": "Taux de guidage",
            "via": "Via",
            "box": "Boîte",
            "effects": "Effets",
            "dither": "Décalage",
            "frequency": "Fréquence",
            "every": "every",
            "frames": "frames",
            "gpg": "GPG",
            "directions": "Directions",
            "dec": "DÉC",
            "swap": "Échanger",
            "east": "+",
            "west": "-",
            "north": "+",
            "south": "-",
            "subframe": "Sous trame",
            "autostar": "Auto Star",
            "aggressiveness": "Gain prop.",
            "rarms": "RA RMS\"",
            "derms": "DE RMS\"",
            "totalrms": "Total RMS\"",
            "advanced": "Avancé",
            "clear_model": "Effacer le modèle d'étalonnage",
            "yAxis": "Dérive (arcsec)"
        },
        "collapse_observatory": {
            "heading": "Observatoire"
        },
        "collapse_polar": {
            "heading": "Alignement polaire",
            "mount_direction": "Direction de la monture",
            "manual_slew": "Déplacement Manuel",
            "west": "Ouest",
            "east": "Est",
            "mount_rotation": "Rotation de la Monture",
            "refresh": "Rafraîchir",
            "fov_error": "Désactivé: le champ de vision doit être de 30 arcmins ou plus.",
            "polar_error": "Erreur polaire :",
            "az_error": "AZ error: ",
            "al_error": "AL error: "
        },
        "collapse_sequence": {
            "progress": "Progression",
            "sequence": "Séquence",
            "overall_progress": "Progression Globale",
            "sequences": "Séquences",
            "no_sequences": "Pas de séquences. Vous pouvez les ajouter en appuyant sur Ajouter à la séquence."
        },
        "collapse_mount": {
            "meridian_flip": "Retournement au Méridien",
            "flip_if_ha": "Retourner si HA>",
            "flip_if_ha_unit": "°",
            "pierside": "Côté de la jetée",
            "auto_park": "Parking automatique",
            "auto_park_everyday": "Tous les jours",
            "park_at": "Parquer à",
            "reset_options": "Réinitialiser les options",
            "min_alt": "Alt min",
            "max_alt": "Alt max",
            "enable_alt_limits": "Activer les limites Alt",
            "enable_ha_limits": "Activer les limites HA",
            "max_ha": "HA max (heures)",
            "clear_model": "Purger Modèle",
            "east": "E",
            "west": "O",
            "east_long": "Est (pointant vers l'ouest)",
            "west_long": "Ouest (pointant vers l'est)",
            "btn_set_auto_park_timer": "Définir l'heure de parquage automatique"
        },
        "modal_add_to_seq": {
            "heading": "Ajouter à la séquence",
        },
        "modal_goto_sync": {
            "heading": "Aller ou synchroniser",
            "category": "Catégorie",
            "btn_goto": "Aller à"
        },
        "mount_status_bar": {
            "ra": "RA",
            "de": "DE",
            "az": "AZ",
            "at": "AL",
            "ha": "HA"
        },
        "camera_status_bar": {
            "bin": "Bin",
        },
        "solution_bar": {
            "dra": "dRA",
            "dde": "dDE",
            "arcsec": "\"",
            "pix": "PIX",
            "rot": "ROT",
            "fov": "FOV",
            "error": "Erreur"
        },
        "mount_overlay": {
            "right_asc": "Asc. Droit.",
            "declination": "Déclinaison",
        },
        "histogram": {
            "mean": "Mean",
            "median": "Median",
            "bit_depth": "Bit Depth",
            "non_linear_histogram": "Histogramme Non-Lineaire"
        },
        "livestacking": {
            "auto_dark": "Auto Dark",
            "plate_solve": "Plate Résoudre",
            "background": "Background",
            "saturation": "Saturation",
            "contrast": "Contraste",
            "sigma_clipping": "Sigma Clipping",
            "noImages": "Pas d'images trouvées pour Live Stacking"
        },
        "scheduler": {
            "scheduler": "PLANIFICATEUR",
            "j2000": "J2000",
            "fits": "FITS File",
            "priority": "Priorité",
            "profile": "Profil",
            "startupConditions": "démarrage",
            "JobConstraints": "Contraintes  des Tâches",
            "completionConditions": "de fin des Tâches",
            "observatoryStartup": "de démarrage de l'Observation",
            "abortedJobManagement": "Gestion des tâches abandonnées",
            "observatoryShutdown": "Arrêt Observation",
            "alt": "Alt >",
            "moon": "Lune >",
            "twilight": "Aube",
            "artifHorizon": "Horizon Artificiel",
            "sequenceCompletion": "Achèvement des Sequences",
            "repeatFor": "Répéter pour",
            "repeatUntilTerminated": "Répéter jusqu'à terminaison",
            "repeatUntil": "Répéter jusqu'à",
            "unparkDome": "Déparduer le Dôme",
            "unparkMount": "Déparquer la Monture",
            "uncap": "Enlever la coiffe",
            "warmCCD": "Réchauffer CCD",
            "none": "None",
            "queue": "Queue",
            "immediate": "Immediate",
            "rescheduleErrors": "Reschedule Errors (seconds wait)",
            "no_jobs": "Pas de Tâche dans la file d'attente",
            "err_loading_folders": "Error loading folders",
            "err_loading_fits": "Error loading .fits files",
            "err_delete_file": "Error deleting file",
            "add_job": "Add Job",
            "start_jobs": "Start & Stop Jobs",
            "culimination": "Culmination Offset",
            create_jobs: "Create Jobs",

            mosaic: {
                import: "Import Mosaic",
                planner: "Mosaic planner"
            }

        },
        summary: {
            empty: "No summary data available",
            deviation: "Deviation",
            inactive: "Inactive"
        }
    },
    "optical_train": {
        "optical_trains": "Optical Trains",
        "telescope": "Telescope / Lens",
        "create_new": "Create New",
        dslr_lens: "DSLR Lens",
        focal_ratio: "Focal Ratio",
        tooltip:{
            title: "Select the device that receives the guiding correction pulses",
            subject: "This can be one of the following devices:",
            mount_device: "If the Mount can receive guiding correction pulses, then it is best to select it so that the pulses are directly sent to the mount. This is the recommended option.",
            st4_device: "If using an ST4 cable between the guide camera and mount, then you should select the Guide Camera as the Guider.",
            dedicated_device: "If using a dedicated guider interface device (like Shoestring GPUSB) then select it as the Guider",
            dedicated: "Dedicated",
            filterWheel: "Select a filter wheel. This must be a standalone filter wheel connected to StellarMate via USB. If you have a filter wheel that is embedded in a camera, leave this field empty."
        }
    },
    "status": {
        "system": "Système",
        "info": "Info",
        "software": "Logiciel",
        "cpu": "CPU",
        "ram": "RAM",
        "storage": "ESPACE DE STOCKAGE",
        "stable": "Stable",
        "beta": "Bêta",
        "wifi_network": "IP du réseau Wifi",
        "ethernet_network": "IP Ethernet",
        "model": "Modèle",
        "version": "Version",
        "hostname": "Nom de l'hôte",
        "time": "Temps",
        "release_type": "Type de version",
        "updates": "Mises à jour",
        "hotspotMode": "Mode point d'accès",
        "wifiNetwork": "Réseau Wifi",
        "wifiBand": "Bande WiFi",
        "update_available": "Nouvelles mises à jour disponibles",
        "btn_vnc": "Bureau (VNC)",
        "btn_web_manager": "Gestionnaire Web",
        "btn_restart": "Redémarrer",
        "btn_shutdown": "Eteindre",
        "btn_manage_wifi": "Gérer le WiFi",
        "btn_enable_direct_ethernet": "Activer Direct Ethernet",
        "btn_disable_direct_ethernet": "Désactiver Direct Ethernet",
        "btn_enable_hotspot": "Activer le point d'accès",
        "btn_disable_hotspot": "Désactiver le point d'accès",
        "btn_change_hostname": "Changer le nom d'hôte",
        "btn_check_for_updates": "Rechercher des mises à jour",
        "btn_update_now": "Mettez à jour maintenant",
        "btn_update_in_progress": "Mise à jour...",
        "btn_factory_reset": "Retour aux paramètres d'usine",
        "btn_change_resolution": "Changer la résolution",
        "btn_later": "Plus tard",
        "btn_resize_fs": "Redimensionner SD",
        "btn_continue": "Continuer",
        "information_ekos_offline": 'Ekos est hors ligne. Please start the equipment profile directly or via the Scheduler.',
        "no_camera_detected": 'Pas de caméra détectée ou Caméra hors ligne.',

        "alert_device_offline_title": "L'appareil est hors ligne",
        "alert_device_offline_body": "L'appareil semble être hors ligne pour le moment. Vous êtes-vous connecté à un appareil?",
        "alert_restart_title": "Redémarrer StellarMate",
        "alert_restart_body": "Votre appareil va maintenant être redémarré. Vous pouvez essayer de vous reconnecter une fois qu'il a redémarré.",
        "alert_shutdown_title": "Arrêter StellarMate",
        "alert_shutdown_body": "Votre appareil va maintenant s'éteindre. Pour pouvoir le réutiliser, vous devrez l'activer manuellement.",
        "alert_resize_title": "Redimensionner la carte microSD",
        "alert_resize_body": "StellarMate s'étendra à la taille complète de la carte SD. Redémarrez StellarMate après le redimensionnement.",
        "alert_resize_btn_resize": "Redimensionner",
        "alert_hotspot_enable_title": "Activation du point d'accès",
        "alert_hotspot_enable_body": "Si vous activez le point d'accès, stellarmate se déconnectera de tout réseau wifi actuellement connecté et démarrera son propre point d'accès. Pour continuer à utiliser StellarMate, vous devez vous connecter au même réseau hotspot depuis votre appareil. Voulez-vous continuer?",
        "alert_hotspot_post_enable_title": "Veuillez vous connecter au hotspot",
        "alert_hotspot_post_enable_body": "Vous pouvez maintenant vous connecter au hotspot «stellarmate» et appuyer sur OK lorsque vous avez terminé pour continuer",
        "alert_hotspot_disable_body": "La désactivation du hotspot permettra à StellarMate de se connecter à son réseau sans fil précédemment mémorisé. Vous devez être sur le même réseau pour continuer à utiliser StellarMate lorsque son hotspot est désactivé. Voulez-vous continuer?",
        "alert_factory_reset_body": "Réinitialisation d'usine terminée. Veuillez redémarrer StellarMate maintenant.",
        "alert_factory_reset_confirmation_body": "Voulez-vous vraiment réinitialiser l'appareil aux paramètres d'usine? Tous les paramètres seront effacés. Cette action est irréversible!",
        "alert_forget_wifi_title": "Oubliez le Wifi",
        "alert_forget_wifi_body": "Tous les réseaux WiFi seront effacés et StellarMate fonctionnera désormais en mode HotSpot. Vous devez basculer vers le réseau hotspot de votre téléphone / tablette. Voulez-vous continuer?",
        "alert_join_wifi_title": "Rejoignez le réseau Wifi",
        "alert_join_wifi_body": "Rejoindre un réseau wifi fermera le hotspot (s'il est démarré) par StellarMate. Pour continuer à utiliser StellarMate, assurez-vous que vous êtes sur le même réseau. Voulez-vous continuer?",
        "alert_change_band_title": "Êtes-vous sûr de vouloir changer de groupe?",
        "alert_change_band_body": "L'application StellarMate peut être déconnectée et le changement de canal peut échouer pour diverses raisons, auquel cas le point d'accès sera restauré aux paramètres par défaut.",
        "alert_change_resolution_title": "Succès!",
        "alert_change_resolution_body": "Vous pouvez maintenant redémarrer StellarMate pour que la résolution prenne effet",
        "alert_change_release_title": "Chaîne bêta",
        "alert_change_release_body": "Voulez-vous vraiment passer à la version bêta instable et non compatible?",
        "alert_direct_ethernet_title": "Ethernet direct",
        "alert_direct_ethernet_connect_body": "Connectez le câble Ethernet directement entre StellarMate et votre PC. Définissez l'adresse IP de votre PC sur 192.168.100.2 et la passerelle sur 192.168.100.1",
        "alert_direct_ethernet_disconnect_body": "Retirez le câble Ethernet direct.",
        "alert_clear_all_driver_config_title": "Effacer toute la configuration du pilote",
        "alert_clear_all_driver_config_body": "Êtes-vous sûr de vouloir supprimer toute la configuration du pilote?",
        "alert_update_complete_title": "SM OS Update",
        "alert_update_complete_body": "Update complete, please restart StellarMate.",
        "alert_network_error_title": "Network error",
        "alert_network_error_body": "Failed to query network information",
        "alert_delete_directory_message": "You want to delete {0} directory and all files under it?",

        alert_permission_title: "Location permission",
        alert_permission_description: "StellarMate App requires Location information to synchronize StellarMate gadget location to the App location. Do you want to proceed?",

        alert_remote_isactive: "Failed to check if Remote support is active, Is your Stellarmate OS up to date? ",
        alert_remote_start: "Could not start the Remote support: ",
        alert_remote_stop: "Could not stop the Remote support: ",
        alert_remote_id: "Could not find Remote support ID", 
        alert_remote_failed: "Failed to get Remote support ID: ",
        alert_remote_not_found: "No Remote support found: ",

        "change_resolution_modal": {
            "mode": "Mode"
        },
        "change_hostname_modal": {
            "new_hostname": "Nouveau nom d'hôte"
        },
        "change_wifi_modal": {
            "heading": "Rejoignez un réseau",
            "ssid": "SSID",
            "err_wifi": "Un problème est survenu lors de la recherche de réseaux Wi-Fi."
        },
        "change_band_modal": {
            "heading": "Changer de bande",
            "band": "Bande",
            "channel": "Canal"
        },
        "vnc_view": {
            "heading": "VNC",
            "alert_unreachable_title": "VNC inaccessible",
            "alert_unreachable_body": "Il semble y avoir un problème lors de la tentative d'établissement de la connexion à la visionneuse VNC"
        },
        "web_manager_view": {
            "alert_unreachable_title": "Gestionnaire Web inaccessible",
            "alert_unreachable_body": "Il semble y avoir un problème lors de la tentative d’établissement de la connexion à Web Manager"
        }
    },
    "settings": {
        "heading": "REGLAGES",
        "language": "Langue",
        "high_bandwidth": "Bande passante élevée",
        "transfer_images": "Transférer des images",
        "notifications": "Notifications",
        "sounds": "Activer le Son",
        "cloud_storage": "Stockage en ligne",
        "auto_sync": "Synchronisation automatique",
        "location": "Emplacement",
        "reset_app": "Réinitialiser l'application",
        "reset_app_body": "Purger tous les paramètres de l'application?"
    },
    "cloud": {
        "heading": "VUE",
        "btn_filters": "Filtres",
        "btn_gallery": "Galerie",
        "btn_offline_viewer": "Visionneuse hors ligne",
        "btn_cloud_viewer": "Cloud Viewer",
        "no_images_title": "Aucune image trouvée",
        "no_images_body": "Essayez de changer les filtres.",
        "no_selected_title": "Aucune image sélectionnée",
        "no_selected_body": "Sélectionnez une image de Galley",
        "cloud_disabled_title": "Le viewer est désactivé",
        "cloud_disabled_body": "Accédez aux paramètres et activez Cloud pour pouvoir accéder à cet onglet.",
        "pro_plan_body": "Le stockage dans le viewer n'est disponible que pour les utilisateurs du plan Pro.",
        "alert_cannot_download_title": "Ne peut pas télécharger",
        "alert_cannot_download_body": "Une erreur s'est produite lors de la tentative de téléchargement.",
        "alert_confirm_delete_title": "Êtes-vous sûr?",
        "alert_confirm_delete_body": "Souhaitez-vous vraiment supprimer {0}? Une fois supprimé, il ne peut plus être récupéré.",
        "filters_drawer": {
            "field": "Champ",
            "condition": "État",
            "value": "Valeur",
            "btn_add_filter": "Ajouter un Filtre",
            "airmass": "Masse d'air",
            "object": "Objet",
            "contains": "Contient"
        },
        "gallery_drawer": {
            "all": "tous",
            "h1": "1h",
            "h24": "24h",
            "d7": "7d",
            "m1": "1m",
            "y1": "1y",
            "images": "Images",
            "btn_sort": "Trier",
            "btn_delete_all": "Supprimer Tout",
            "ascending": "A-Z",
            "descending": "Z-A",
            "alert_no_images_title": "Aucune image",
            "alert_no_images_body": "Il n'y a aucune image dans la galerie qui pourrait être supprimée.",
            "alert_delete_all_body": "Voulez-vous vraiment supprimer {0} image (s)? C'est une opération irréversible."
        },
        "info_drawer": {
            "add_tags_here": "Ajoutez des tags ici",
            "captured_on": "Capturé sur"
        }
    },
    "about": {
        "heading": "À propos",
        "bundle": "Paquet",
        "copyright_line1": "StellarMate est développé par Ikarus Technologies © 2017-2022",
        "copyright_line2": "Image d'arrière-plan par l'Observatoire Alamri"
    },
    "messages": {
        "polar_idle": "Cette outil propose une méthode simple pour l'alignement polaire des monture équatoriale Allemande. Parquer votre monture vers l'étoile polaire ave le contre-poids vers le bas. Sélectionnez la direction et la vitesse de la monture, puis cliquez sur Démarrer pour commencer le processus. Si vous n'avez pas de vue sur le pôle, utilisez le contrôle de la monture avec Carte Du Ciel ou Ekos pour pointer n'importe où, de préférence près du méridien, choisissez Est ou Ouest selon votre côté, diminuez l'angle de rotation si nécessaire, et cliquez sur Démarrer.",
        "alert_directions_not_found": "Coordinates not found, Please frame your target or enter coordinates manually.",
        "manual_rotator": "Rotate camera by the indicated angle and then take an image to update the position angle",
        "welcome": "Welcome to StellarMate"
    },
    "ekosLivePro": {
        "pushNotification": "Push Notification",
        "level": "Notification Level",
        "settings": "EkosLive Pro Settings"
    }
};

export default fr;
