const fr = {
    "general": {
       "home": "Accueil",
       "next": "prochain",
       "ok": "D'accord",
       "done": "Fait",
       "cancel": "Annuler",
       "apply": "Appliquer",
       "save": "sauvegarder",
       "select": "Sélectionner",
       "connect": "Connecter",
       "disconnect": "Déconnecter",
       "yes": "Oui",
       "no": "Non",
       "error": "Erreur",
       "back": "Retour",
       "delete": "Supprimer",
       "remove": "Retirer",
       "online": "En ligne",
       "offline": "Hors ligne",
       "remote": "Distant",
       "preset": "Préréglage",
       "camera": "Caméra",
       "focuser": "Focuser",
       "filter_wheel": "Roue à filtre",
       "filter": "Filtre",
       "exposure": "Exposition",
       "binning": "Binning",
       "action": "Action",
       "scope_type": "Type de portée",
       "solver_type": "Type de solveur",
       "type": "Type",
       "gain": "Gain",
       "offset": "Décalage",
       "format": "Format",
       "iso": "ISO",
       "count": "Nombre",
       "delay": "Retard",
       "status": "Statut",
       "target": "Cible",
       "angle": "Angle",
       "sep_profile": "Profil SEP",
       "direction": "Direction",
       "rotation": "Rotation",
       "automatic": "Automatique",
       "manual": "Manuel",
       "progress": "Progress",

       "azimuth": "Azimut",
       "altitude": "Altitude",
       "tags": "Mots clés",
       "filename": "Nom du fichier",
       "size": "Taille",
       "frame": "Cadre",
       "temperature": "Température",
       "name": "Nom",
       "date": "Date",
       "resolution": "Résolution",
       "select_option": "Sélectionnez l'option...",
       "search": "Chercher...",
       "no_results": "Aucun résultat",
       "on": "Marche",
       "off": "Arrêt",
       "go": "ALLER",
       "add": "AJOUTER",
       "edit": "ÉDITER",
       "refresh": "RAFRAÎCHIR",
       "reset": "RÉINITIALISER",
       "reset_all": "Tout réinitialiser",
       "start": "DÉBUT",
       "stop": "Arrêtez",
       "stopping": "Arrêt",
       "clear": "Effacer",
       "solve": "RÉSOUDRE",
       "parked": "Parquée",
       "unparked": "Dé Parquée",
       "open": "Ouvrir",
       "close": "Fermé",
       "opened": "Ouvrir",
       "closed": "Fermé",
       "enable": "Activer",
       "disable": "Désactiver",
       "selectTime": "Durée",
       "set": "Ensemble",

       // Confirm Delete Alert
       "alert_confirm_delete_title": "Confirmer Suppression",
       "alert_delete_profile_body": "Voulez-vous vraiment supprimer le profil sélectionné ?",
       "alert_delete_scope_body": "Êtes-vous sûr de vouloir supprimer le scope sélectionné?",

       "network_error": "Veuillez vous assurer que votre StellarMate est connecté à votre réseau",
       "internet_required": "Veuillez vous assurer que vous êtes connecté à Internet",
       "alert_comm_error_title": "Erreur de communication",
       "alert_comm_error_body": "Échec de la communication avec StellarMate. Veuillez vous assurer qu'il est connecté à votre réseau.",
       "ekoslive_down_title": "EkosLive est en panne",
       "ekoslive_down_body": "EkosLive n'est pas en cours d'exécution, essayez de redémarrer StellarMate ou contactez l'assistance StellarMate.",
       "kstars_down_title": "KStars est en panne",
       "kstars_down_body": "KStars n'est pas en cours d'exécution, essayez de redémarrer StellarMate ou contactez le support StellarMate.",
       "reset_default": "Reset to default",
       "external_storage": "Stokage Externe"
    },
    "darkLibrary":{
      "title": "Dark Library",
      "darks": "Darks",
      "defects": "Defects",
      "prefer": "Prefer",
      "create_darks_title": "Créer Darks",
      "create_defects_title": "Créer la Defect Map",
      "view_masters_title": "View Masters",
      "progress": "Progression",

      "create_darks":{
          "exposure_range": "Plage d'expo.",
          "to": "à",
          "temp_range": "Plage de temp.",
          "binning": "Binning",
          "binningOne": "1x1",
          "binningTwo": "2x2",
          "binningFour": "4x4",
          "total_images": "Total",
      },

      "create_defect_map":{
          "master_dark": "Master Dark",
          "bad_pixels": "Bad Pixels",
          "hot_pixels": "Pixels chauds",
          "generate_map": "Generer carte",
          "save_map": "Sauvegardé",
          "deviation": "σ"
      },   
  },
    "splash": {
       "checking_for_updates": "Vérification des mises à jour...",
       "downloading_package": "Téléchargement de la mise à jour...",
       "installing_update": "Installation de mise à jour...",
       "channel_update": "Changement de canal en cours...",
       "upto_date": "Déjà à jour.",
       "update_installed": "Toutes les mises à jour installées.",
       "loading": "Chargement..."
    },
    "validations": {
       "username_required": "Le nom d'utilisateur est obligatoire",
       "username_tooshort": "Minimum 3 caractères requis",
       "username_toolong": "Ne peut pas contenir plus de 64 caractères",
       "username_invalid": "Caractères non valides dans le nom d'utilisateur",
       "password_required": "Mot de passe requis",
       "password_invalid": "Minimum 6 caractères requis",
       "confirm_password_required": "Confirmer le mot de passe requis",
       "confirm_password_mismatch": "Confirmer le mot de passe incorrect",
       "email_required": "Email (requis",
       "email_invalid": "Adresse e-mail invalide",
       "license_required": "Clé de licence requise",
       "serial_required": "Clé de série requise",
       "new_scope_vendor": "Entre un nom de fournisseur valide",
       "new_scope_model_invalid": "Entre un modèle valide",
       "new_scope_aperture_invalid": "Entre une ouverture valide",
       "new_scope_focal_length_invalid": "Entre une focale valide"
    },
    "progress": {
       "please_wait": "S'il vous plaît, attendez ...",
       "establishing_connection": "Établissement de la connexion",
       "cameras": "Obtenir des caméras",
       "mounts": "Obtenir des montures",
       "scopes": "Obtenir des portées",
       "filter_wheels": "Obtenir des roues de filtre",
       "registering": "Enregistrement...",
       "registered": "inscrit",
       "authenticating": "Authentification...",
       "authenticated": "Authentifié",
       "checking_kstars": "Vérification de KStars...",
       "kstars_open": "KStars ouvert",
       "checking_ekoslive": "Vérification d'EkosLive...",
       "ekoslive_connected": "EkosLive connecté",
       "starting_ekos": "Démarrer Ekos...",
       "getting_devices": "Obtenir des appareils...",
       "loading_settings": "Chargement des paramètres..."
    },
    "welcome": {
       "register_new_device": "Enregistrer un nouvel appareil?",
       "have_existing_account": "Vous avez un compte existant?",
       "require_sm_plus_pro": "Inscrivez-vous si vous avez"
    },
    "device_scanner": {
       "scanning": "Veuillez patienter pendant que nous recherchons des appareils StellarMate sur le réseau",
       "qr_scan": "Scannez le code QR de votre appareil "
    },
    "statuses": {
       "Idle": "Tourner au ralenti",
       "Aborted": "Avorté",
       "Calibration error": "Erreur d'étalonnage",
       "Capturing": "Capturer",
       "In Progress": "En cours",
       "Setting Temperature": "Réglage de la température",
       "Slewing": "Pivotement",
       "Calibrating": "Étalonnage",
       "Tracking": "Poursuite",
       "Guiding": "Guidage",
       "Parking": "Parking",
       "User Input": "Entrée utilisateur",
       "Complete": "Compléter",
       "Suspended": "Suspendu",
       "Parked": "Garé"
    },
    "connect": {
       "register_welcome": "Veuillez vous connecter à votre compte stellarmate.com pour synchroniser les appareils.",
       "welcome_heading": "Salut!",
       "welcome_description": "Veuillez vous assurer que vous êtes connecté au HotSpot de StellarMate ou que StellarMate est sur le même réseau que vous.",
       "welcome_rescan": "Cliquez sur RESCAN pour commencer à scanner le réseau pour les appareils StellarMate.",
       "device_unreachable": "L'appareil n'est pas accessible! Vérifiez les paramètres d'alimentation et de réseau.",
       "login_mismatch": "Authentification échouée. Le mot de passe de l'application est différent du mot de passe en ligne de stellarmate.com. Enregistrez à nouveau l'application avec le mot de passe en ligne correct.",
       "old_stellarmate_heading": "Mise à jour requise!",
       "old_stellarmate_description": "Vous semblez utiliser une ancienne version de StellarMate OS. Vous devez passer à la version la plus récente de StellarMate pour continuer à utiliser cette application.",
       "primary": "Primaire",
       "guide": "Guider",
       "scope": "Portée",
       "btn_rescan": "RESCAN",
       "btn_port_select": "Selection de port",
       "btn_sync_gps": "Synchroniser le GPS",
       "btn_dslr_setup": "Configuration DSLR",
       "btn_clear_driver_config": "Effacer la configuration du pilote.",
       "scan_in_progress": "Analyse en cours ...",
       "connection_in_progress": "Connexion de StellarMate ...",
       "registration_in_progress": "Enregistrement de StellarMate ...",
       "logging_in_progress": "Connexion à StellarMate ...",
       "connecting": "De liaison...",
       "logging": "Enregistrement...",
       "ip_address": "Adresse IP",
       "login_register": {
          "heading": "Authentifier",
          "heading_online": "Connectez-vous à stellarmate.com",
          "connect_to_internet": "Vous devez être connecté à Internet.",
          "connect_to_sync": "Cela n'est fait qu'une seule fois pour synchroniser votre compte.",
          "reset_app": "Conseil: vous pouvez resynchroniser l'application avec votre compte en ligne en accédant à l'onglet À propos et en cliquant sur Bouton de réinitialisation de l'application, puis relance de l'application",
          "no_valid_device": "Aucune information valide sur l'appareil disponible.",
          "setup_guide": "Guide d'installation",
          "register": "S'inscrire",
          "login": "Se connecter",
          "serial": "Numéro de série",
          "license": "Clé de licence",
          "username": "Nom d'utilisateur",
          "password": "Mot de passe",
          "confirm_password": "Confirmez le mot de passe",
          "first_name": "Prénom",
          "last_name": "Nom",
          "email": "Email"
       },
       "device_manager": {
          "alert_confirm_remove_title": "Confirmer la suppression",
          "alert_confirm_remove_body": "Voulez-vous vraiment supprimer cet appareil?",
          "btn_sign_out": "Déconnexion"
       },
       "profile_manager": {
          "heading": "Profils d'équipement"
       },
       "port_selector": {
          "connect_all": "Tout connecter"
       },
       "manually_add_device": {
          "heading": "Ajouter manuellement un appareil",
          "btn_add_device": "Ajouter un appareil",
          "alert_unreachable_title": "Une erreur s'est produite",
          "alert_unreachable_body": "Une erreur s'est produite lors de la tentative de localisation du périphérique à l'adresse IP spécifiée. Veuillez vérifier à nouveau l'adresse IP et réessayer."
       },
       "device_scanner": {
          "no_device_before_scan": "Aucun appareil détecté. Exécutez le scanner.",
          "no_device_after_scan": "Analyse terminée. Aucun périphérique trouvé.",
          "auto_scanned": "Analyse automatique",
          "manually_added": "Ajouté manuellement",
          "add_a_device": "Ajouter un périphérique",
          "devices_detected": "Appareil détecté",
          "no_network_found": "Aucun réseau détecté. Assurez-vous que vous êtes connecté à un réseau."
       },
       "add_profile": {
          "add_profile": "Ajouter un profil",
          "edit_profile": "Editer le profil",
          "mount": "Monture",
          "ccd": "CCD",
          "guider": "Guider",
          "ao": "Optique adaptative",
          "weather": "Météo",
          "aux1": "Aux1",
          "aux2": "Aux2",
          "aux3": "Aux3",
          "aux4": "Aux4"
       },
       "add_scope": {
          "add_scope": "Ajouter un télescope",
          "edit_scope": "Modifier le télescope",
          "vendor": "Fabricant",
          "aperture": "Ouverture (mm)",
          "focal_length": "Distance focale (mm)"
       },
       "auto_detect": {
          "alert_auto_detect_title": "Instructions de détection automatique",
          "alert_auto_detect_body": "Débranchez TOUS les équipements de StellarMate puis appuyez sur Ok. Puis branchez-les un par un pour détecter le type de périphérique et le pilote. Une fois que chaque périphérique est branché, vous devez confirmer le pilote.",
          "alert_mapped_title": "Cartographie des appareils",
          "alert_mapped_body": "Le port série de l'appareil est correctement mappé.",
          "alert_missing_driver_title": "Pilote manquant",
          "alert_missing_driver_body": "Vous devez d'abord sélectionner un pilote."
       },
       "dslr_setup": {
          "width": "Largeur",
          "height": "la taille",
          "pixel_width": "Largeur de pixel",
          "pixel_height": "Hauteur de pixel"
       }
    },
    "targets": {
       "now": "Maintenant",
       "night": "Nuit",
       "rise": "Lever",
       "moon": "Lune",
       "sun": "Soleil",
       "search": "Chercher",
       "phases": {
          "new_moon": "Nouvelle Lune",
          "full_moon": "Pleine Lune",
          "first_quarter": "Premier Quartier",
          "third_quarter": "Dernier Quartier",
          "waxing_crescent": "Premier croissant",
          "waxing_gibbous": "Gibbeuse croissante",
          "waning_crescent": "Dernier croissant",
          "waning_gibbous": "Gibbeuse décroissante"
       },
       "lists": "Lists",
       "framing_assistant": "Framing Assistant",
       "target_rotation": "Target Position Angle",
       "current_rotation": "Current Rotation",
       "rotate_capture": "Rotate & Capture",
       "goto_rotate": "GOTO & Rotate",
       "angular_offset": "Angular Offset",
       "no_objects_in_list": "Pas d'objets trouvés, ajuster ou reinitialiser les filtres.",
       "go_and_solve": "Go & Solve",
       "fov_profile": "FOV Profile",
       "fov_width": "FOV Width",
       "fov_height": "FOV Height"
    },
    "ekos": {
       "heading": "Ekos",
       "tgl_mount": "MONTURE",
       "tgl_solution_bar": "BARRE DE SOLUTION",
       "tgl_sequence": "SÉQUENCE",
       "tgl_properties": "PROPRIÉTÉS",
       "alert_ekos_offline_title": "Ekos est hors ligne",
       "alert_ekos_offline_body": "Ekos semble être hors ligne pour le moment. Avez-vous commencé le profil d'équipement?",
       "ekos_dialog": {
          "auto_closes_in": "Fermeture automatique dans"
       },
       "controls_bar": {
          "mount_speed": "Vitesse de la monture",
          "centering": "Centrage",
          "find": "Trouver",
          "max": "Max"
       },
       "collapse_align": {
          "heading": "Aligner",
          "action_sync": "Synchroniser",
          "action_slew": "Viser vers la cible",
          "action_nothing": "Rien",
          "solver_backend": "Backend",
          "control": "Contrôle",
          "solve": "Capturer et résoudre",
          "load": "Charger et faire pivoter",
          "polar": "Alignement Polaire",
          "accuracy": "Précision",
          "settle": "Régler",
          "dark": "Dark",
          "arcsec": "arcsec",
          "ms": "SP",
          "xAxis": "Itérations",
          "yAxis": "Erreur (arcsec)",
          "refresh_rate": "Taux de rafraichissement",
          "manualRotator": {
            "heading": "Manual Rotator",
            "currentPA": "Current PA",
            "targetPA": "Target PA",
            "another_image": "Take another Image",
        },
        "alignSettings": {
         "rotator_control": "Rotator Control",
         "use_scale": "Use Scale",
         "use_position": "Use Position"
     }
       },
       "collapse_camera": {
          "heading": "Capturer",
          "type_light": "Light",
          "type_bias": "Biais",
          "type_flat": "Flat",
          "format_fits": "Fits",
          "format_native": "Natif",
          "cooling_unavailable": "N/A",
          "btn_add_to_sequence": "Ajouter à la séquence ",
          "btn_loop": "Boucle"
       },
       "capture_presets": {
          "heading": "Paramètres prédéfinis"
       },
       "capture_limits": {
          "heading": "Limiter les paramètres",
          "guiding_deviation": "Écart de guidage <",
          "guiding_deviation_unit": "\"",
          "focusHFR": "Autofocus si HFR>",
          "focusHFR_unit": "pixels",
          "focusDeltaT": "Autofocus si ΔT °>",
          "focusDeltaT_unit": "°C",
          "refocusN": "Recentrer chaque",
          "refocusN_unit": "minutes"
       },
       "capture_filters": {
          "heading": "Paramètres de filtre",
          "auto_focus": "Mise au point automatique",
          "lock_filter": "Verrouiller le filtre"
       },
       "targets_filters": {
          "object_type": "Type d'objet",
          "alt": "Alt"
       },
       "capture_auto_calibration": {
          "heading": "Calibration automatique",
          "flat_source": "Source de Flat",
          "flat_duration": "Durée Flat",
          "dust_builtin": "Cache-poussière avec éclairage plat intégré",
          "dust_external": "Cache-poussière avec éclairage plat externe",
          "wall": "mur",
          "az": "Az",
          "adu": "ADU",
          "tolerance": "Tolérance",
          "parkMount": "Monture parquée",
          "parkDome": "Dome fermé",
          "manual": "Manuel"
       },
       "capture_file": {
          "filename": "Nom du Fichier",
          "heading": "Paramètres de fichier",
          "prefix": "Préfixe",
          "script": "Scénario",
          "directory": "répertoire",
          "ts": "TS",
          "duration": "Durée"
       },
       "collapse_dome": {
          "heading": "Cap et Dôme",
          "cap": "Casquette",
          "dome": "Dôme",
          "shutter": "Obturateur",
          "domeSlaving": "Asservissement du dôme",
          "params": "Paramètres",
          "measurements": "Mesures",
          "autosync_threshold": "Seuil de synchronisation automatique (deg)",
          "radius": "Rayon (m)",
          "shutter_width": "Largeur d'obturation (m)",
          "n_displacement": "N Déplacement (m)",
          "e_displacement": "Déplacement E (m)",
          "up_displacement": "Déplacement vers le haut (m)",
          "ota_offset": "Décalage OTA (m)"
       },
       "collapse_focus": {
          "heading": "Concentrer",
          "hfr": "HFR",
          "hfr_plot": "Tracé HFR",
          "focus_in": "Dans",
          "focus_out": "En dehors",
          "steps": "Pas",
          "settings": {
             "suspendGuiding": "Suspendre le guidage",
             "autoSelectStar": "Etoile selectionnée automatiquement",
             "subframe": "Sous-Trame",
             "fullfield": "Plein Champ",
             "dark": "Dark",
             "annulus": "Anneau",
          },
          "process": {
             "title": "Traiter",
             "detection": "Détection",
             "algorithm": "Algorithme",
             "threshold": "Seuil",
             "effect": "Effet",
             "averageOver": "Moyenne sur",
             "kernelSize": "Taille du noyau",
             "numOfRows": "Nombre",
             "sigma": "Sigma"
          },
          "mechanics": {
             "title": "Mécanique",
             "initialStepSize": "Taille initiale de pas",
             "maxTravel": "Trajet maximum",
             "maxStepSize": "Taille maximale du pas",
             "backlash": "Backlash",
             "outStepMultiple": "délai déplacement dépassé"
          }
       },
       "collapse_guide": {
          "total_rms_plot": "RMS",
          "scope_primary": "Primaire",
          "guidingRate": "Taux de guidage",
          "via": "Via",
          "box": "Boîte",
          "effects": "Effets",
          "dither": "Décalage",
          "frequency": "Frequence",
          "every": "every",
          "frames": "frames",
          "gpg": "GPG",
          "directions": "Directions",
          "dec": "DÉC",
          "swap": "Échanger",
          "east": "+",
          "west": "-",
          "north": "+",
          "south": "-",
          "subframe": "Sous trame",
          "autostar": "Auto Star",
          "aggressiveness": "Gain prop.",
          "rarms": "RA RMS\"",
          "derms": "DE RMS\"",
          "totalrms": "Total RMS\"",
          "advanced": "Avancé",
          "clear_model": "Effacer le modèle d'étalonnage",
          "yAxis": "Dérive (arcsec)"
       },
       "collapse_observatory": {
          "heading": "Observatoire"
       },
       "collapse_polar": {
          "heading": "Alignement polaire",
          "mount_direction": "Direction du montage",
          "manual_slew": "Manual Slew",
          "west": "Ouest",
          "east": "est",
          "mount_rotation": "Rotation du support",
          "refresh": "Rafraîchir",
          "fov_error": "Désactivé: le champ de vision doit être de 30 arcmins ou plus.",
          "polar_error": "Erreur polaire :",
          "az_error": "AZ error: ",
          "al_error": "AL error: "
       },
       "collapse_sequence": {
          "progress": "Progression",
          "sequence": "Séquence",
          "overall_progress": "Les progrès d'ensemble",
          "sequences": "Séquences",
          "no_sequences": "Pas de séquences. Vous pouvez les ajouter en appuyant sur Ajouter à la séquence."
       },
       "collapse_mount": {
          "meridian_flip": "Meridian Flip",
          "flip_if_ha": "Retourner si HA>",
          "flip_if_ha_unit": "°",
          "pierside": "Côté de la jetée",
          "auto_park": "Parc automatique",
          "auto_park_everyday": "Tous les jours",
          "park_at": "Parquer à",
          "reset_options": "Réinitialiser les options",
          "min_alt": "Alt min",
          "max_alt": "Alt max",
          "enable_alt_limits": "Activer les limites Alt",
          "enable_ha_limits": "Activer les limites HA",
          "max_ha": "HA max (heures)",
          "clear_model": "Modèle clair",
          "east": "E",
          "west": "W",
          "east_long": "Est (pointant vers l'ouest)",
          "west_long": "Ouest (pointant vers l'est)",
          "btn_set_auto_park_timer": "Définir l'heure de parquage automatique"
       },
       "modal_add_to_seq": {
          "heading": "Ajouter à la séquence",
       },
       "modal_goto_sync": {
          "heading": "Aller ou synchroniser",
          "category": "Catégorie",
          "btn_goto": "Aller à"
       },
       "mount_status_bar": {
          "ra": "RA",
          "de": "DE",
          "az": "AZ",
          "at": "AL",
          "ha": "HA"
       },
       "camera_status_bar": {
          "bin": "Bin",
       },
       "solution_bar": {
          "dra": "dRA",
          "dde": "dDE",
          "arcsec": "\"",
          "pix": "PIX",
          "rot": "ROT",
          "fov": "FOV",
          "error": "Erreur"
       },
       "mount_overlay": {
          "right_asc": "Asc. Droit.",
          "declination": "Déclinaison",
       },
       "histogram": {
          "mean": "Mean",
          "median": "Median",
          "bit_depth": "Bit Depth",
          "non_linear_histogram": "Histogramme Non-Linear"
       },
       "livestacking": {
         "auto_dark": "Auto Dark",
         "plate_solve": "Plate Solve",
         "background": "Background",
         "saturation": "Saturation",
         "contrast": "Contraste",
         "sigma_clipping": "Sigma Clipping",
         "noImages": "No Live Stacking Images found"
      },
      "scheduler": {
         "scheduler": "Scheduler",
         "j2000": "J2000",
         "fits": "FITS File",
         "priority": "Priority",
         "profile": "Profile",
         "startupConditions": "Job Startup Conditions",
         "JobConstraints": "Job Constraints",
         "completionConditions": "Job Completion Conditions",
         "observatoryStartup": "Observatory Startup Procedure",
         "abortedJobManagement": "Aborted Job Management",
         "observatoryShutdown": "Observatory Shutdown",
         "alt": "Alt >",
         "moon": "Moon >",
         "twilight": "Twilight",
         "artifHorizon": "Artificial Horizon",
         "sequenceCompletion": "Sequence Completion",
         "repeatFor": "Repeat for",
         "repeatUntilTerminated": "Repeat Until Terminated",
         "repeatUntil": "Repeat until",
         "unparkDome": "UnPark Dome",
         "unparkMount": "UnPark Mount",
         "uncap": "UnCap",
         "warmCCD": "Warm CCD",
         "none": "None",
         "queue": "Queue",
         "immediate": "Immediate",
         "rescheduleErrors": "Reschedule Errors (seconds wait)",
         "no_jobs": "No Jobs in the queue",
         "err_loading_folders": "Error loading folders",
         "err_loading_fits": "Error loading .fits files",
         "err_delete_file": "Error deleting file",
     },
    },
    "status": {
       "system": "Système",
       "info": "Info",
       "software": "Logiciel",
       "cpu": "CPU",
       "ram": "RAM",
       "storage": "ESPACE DE STOCKAGE",
       "stable": "Stable",
       "beta": "Bêta",
       "wifi_network": "IP du réseau Wifi",
       "ethernet_network": "IP Ethernet",
       "model": "Modèle",
       "version": "Version",
       "hostname": "Nom d'hôte",
       "time": "Temps",
       "release_type": "Type de version",
       "updates": "Mises à jour",
       "hotspotMode": "Mode point d'accès",
       "wifiNetwork": "Réseau Wifi",
       "wifiBand": "Bande WiFi",
       "update_available": "Nouvelles mises à jour disponibles",
       "btn_vnc": "Bureau (VNC)",
       "btn_web_manager": "Gestionnaire Web",
       "btn_restart": "Redémarrer",
       "btn_shutdown": "Eteindre",
       "btn_manage_wifi": "Gérer le WiFi",
       "btn_enable_direct_ethernet": "Activer Direct Ethernet",
       "btn_disable_direct_ethernet": "Désactiver Direct Ethernet",
       "btn_enable_hotspot": "Activer le point d'accès",
       "btn_disable_hotspot": "Désactiver le point d'accès",
       "btn_change_hostname": "Changer le nom d'hôte",
       "btn_check_for_updates": "Rechercher des mises à jour",
       "btn_update_now": "Mettez à jour maintenant",
       "btn_update_in_progress": "Mise à jour...",
       "btn_factory_reset": "Retour aux paramètres d'usine",
       "btn_change_resolution": "Changer la résolution",
       "btn_later": "Plus tard",
       "btn_resize_fs": "Redimensionner SD",
       "btn_continue": "Continuer",
       "information_ekos_offline": 'Ekos is offline. Please start the equipment profile directly or via the Scheduler.',
       "no_camera_detected": 'No cameras detected or camera offline.',
       
       "alert_device_offline_title": "L'appareil est hors ligne",
       "alert_device_offline_body": "L'appareil semble être hors ligne pour le moment. Vous êtes-vous connecté à un appareil?",
       "alert_restart_title": "Redémarrer StellarMate",
       "alert_restart_body": "Votre appareil va maintenant être redémarré. Vous pouvez essayer de vous reconnecter une fois qu'il a redémarré.",
       "alert_shutdown_title": "Arrêter StellarMate",
       "alert_shutdown_body": "Votre appareil va maintenant s'éteindre. Pour pouvoir le réutiliser, vous devrez l'activer manuellement.",
       "alert_resize_title": "Redimensionner la carte microSD",
       "alert_resize_body": "StellarMate s'étendra à la taille complète de la carte SD. Redémarrez StellarMate après le redimensionnement.",
       "alert_resize_btn_resize": "Redimensionner",
       "alert_hotspot_enable_title": "Activation du point d'accès",
       "alert_hotspot_enable_body": "Si vous activez le point d'accès, stellarmate se déconnectera de tout réseau wifi actuellement connecté et démarrera son propre point d'accès. Pour continuer à utiliser StellarMate, vous devez vous connecter au même réseau hotspot depuis votre appareil. Voulez-vous continuer?",
       "alert_hotspot_post_enable_title": "Veuillez vous connecter au hotspot",
       "alert_hotspot_post_enable_body": "Vous pouvez maintenant vous connecter au hotspot «stellarmate» et appuyer sur OK lorsque vous avez terminé pour continuer",
       "alert_hotspot_disable_body": "La désactivation du hotspot permettra à StellarMate de se connecter à son réseau sans fil précédemment mémorisé. Vous devez être sur le même réseau pour continuer à utiliser StellarMate lorsque son hotspot est désactivé. Voulez-vous continuer?",
       "alert_factory_reset_body": "Réinitialisation d'usine terminée. Veuillez redémarrer StellarMate maintenant.",
       "alert_factory_reset_confirmation_body": "Voulez-vous vraiment réinitialiser l'appareil aux paramètres d'usine? Tous les paramètres seront effacés. Cette action est irréversible!",
       "alert_forget_wifi_title": "Oubliez le Wifi",
       "alert_forget_wifi_body": "Tous les réseaux WiFi seront effacés et StellarMate fonctionnera désormais en mode HotSpot. Vous devez basculer vers le réseau hotspot de votre téléphone / tablette. Voulez-vous continuer?",
       "alert_join_wifi_title": "Rejoignez le réseau Wifi",
       "alert_join_wifi_body": "Rejoindre un réseau wifi fermera le hotspot (s'il est démarré) par StellarMate. Pour continuer à utiliser StellarMate, assurez-vous que vous êtes sur le même réseau. Voulez-vous continuer?",
       "alert_change_band_title": "Êtes-vous sûr de vouloir changer de groupe?",
       "alert_change_band_body": "L'application StellarMate peut être déconnectée et le changement de canal peut échouer pour diverses raisons, auquel cas le point d'accès sera restauré aux paramètres par défaut.",
       "alert_change_resolution_title": "Succès!",
       "alert_change_resolution_body": "Vous pouvez maintenant redémarrer StellarMate pour que la résolution prenne effet",
       "alert_change_release_title": "Chaîne bêta",
       "alert_change_release_body": "Voulez-vous vraiment passer à la version bêta instable et non compatible?",
       "alert_direct_ethernet_title": "Ethernet direct",
       "alert_direct_ethernet_connect_body": "Connectez le câble Ethernet directement entre StellarMate et votre PC. Définissez l'adresse IP de votre PC sur 192.168.100.2 et la passerelle sur 192.168.100.1",
       "alert_direct_ethernet_disconnect_body": "Retirez le câble Ethernet direct.",
       "alert_clear_all_driver_config_title": "Effacer toute la configuration du pilote",
       "alert_clear_all_driver_config_body": "Êtes-vous sûr de vouloir supprimer toute la configuration du pilote?",
       "alert_update_complete_title": "SM OS Update",
       "alert_update_complete_body": "Update complete, please restart StellarMate.",
       "alert_network_error_title": "Network error",
       "alert_network_error_body": "Failed to query network information",
       "change_resolution_modal": {
          "mode": "Mode"
       },
       "change_hostname_modal": {
          "new_hostname": "Nouveau nom d'hôte"
       },
       "change_wifi_modal": {
          "heading": "Rejoignez un réseau",
          "ssid": "SSID",
          "err_wifi": "Un problème est survenu lors de la recherche de réseaux Wi-Fi."
       },
       "change_band_modal": {
          "heading": "Changer de bande",
          "band": "Bande",
          "channel": "Canal"
       },
       "vnc_view": {
          "heading": "VNC",
          "alert_unreachable_title": "VNC inaccessible",
          "alert_unreachable_body": "Il semble y avoir un problème lors de la tentative d'établissement de la connexion à la visionneuse VNC"
       },
       "web_manager_view": {
          "alert_unreachable_title": "Gestionnaire Web inaccessible",
          "alert_unreachable_body": "Il semble y avoir un problème lors de la tentative d’établissement de la connexion à Web Manager"
       }
    },
    "settings": {
       "heading": "Réglages",
       "language": "Langue",
       "high_bandwidth": "Bande passante élevée",
       "transfer_images": "Transférer des images",
       "notifications": "Notifications",
       "sounds": "Des sons",
       "cloud_storage": "Stockage en ligne",
       "auto_sync": "Synchronisation automatique",
       "location": "Emplacement",
       "reset_app": "Réinitialiser l'application",
       "reset_app_body": "Purger tous les paramètres de l'application?"
    },
    "cloud": {
       "heading": "Vue",
       "btn_filters": "Filtres",
       "btn_gallery": "Galerie",
       "btn_offline_viewer": "Visionneuse hors ligne",
       "btn_cloud_viewer": "Cloud Viewer",
       "no_images_title": "Aucune image trouvée",
       "no_images_body": "Essayez de changer les filtres.",
       "no_selected_title": "Aucune image sélectionnée",
       "no_selected_body": "Sélectionnez une image de Galley",
       "cloud_disabled_title": "Le viewer est désactivé",
       "cloud_disabled_body": "Accédez aux paramètres et activez Cloud pour pouvoir accéder à cet onglet.",
       "pro_plan_body": "Le stockage dans le viewer n'est disponible que pour les utilisateurs du plan Pro.",
       "alert_cannot_download_title": "Ne peut pas télécharger",
       "alert_cannot_download_body": "Une erreur s'est produite lors de la tentative de téléchargement.",
       "alert_confirm_delete_title": "Êtes-vous sûr?",
       "alert_confirm_delete_body": "Souhaitez-vous vraiment supprimer {0}? Une fois supprimé, il ne peut plus être récupéré.",
       "filters_drawer": {
          "field": "Champ",
          "condition": "État",
          "value": "Valeur",
          "btn_add_filter": "AJOUTER UN FILTRE",
          "airmass": "Masse d'air",
          "object": "Objet",
          "contains": "Contient"
       },
       "gallery_drawer": {
          "all": "tous",
          "h1": "1h",
          "h24": "24h",
          "d7": "7d",
          "m1": "1m",
          "y1": "1y",
          "images": "Images",
          "btn_sort": "TRIER",
          "btn_delete_all": "SUPPRIMER TOUT",
          "ascending": "A-Z",
          "descending": "Z-A",
          "alert_no_images_title": "Aucune image",
          "alert_no_images_body": "Il n'y a aucune image dans la galerie qui pourrait être supprimée.",
          "alert_delete_all_body": "Voulez-vous vraiment supprimer {0} image (s)? C'est une opération irréversible."
       },
       "info_drawer": {
          "add_tags_here": "Ajoutez des tags ici",
          "captured_on": "Capturé sur"
       }
    },
    "about": {
       "heading": "À propos",
       "bundle": "Paquet",
       "copyright_line1": "StellarMate est développé par Ikarus Technologies © 2017-2022",
       "copyright_line2": "Image d'arrière-plan par l'Observatoire Alamri"
    },
    "messages": {
       "polar_idle": "Cette outil propose une méthode simple pour l'alignement polaire des monture équatoriale Allemande. Parquer votre monture vers l'étoile polaire ave le contre-poids vers le bas. Sélectionnez la direction et la vitesse de la monture, puis cliquez sur Démarrer pour commencer le processus. Si vous n'avez pas de vue sur le pôle, utilisez le contrôle de la monture avec Carte Du Ciel ou Ekos pour pointer n'importe où, de préférence près du méridien, choisissez Est ou Ouest selon votre côté, diminuez l'angle de rotation si nécessaire, et cliquez sur Démarrer.",
       "alert_directions_not_found": "Coordinates not found, Please frame your target or enter coordinates manually."
    }
 };

export default fr;
